### ISSUE TITLE
Fails to highlight first struct and wrongly marks final end as invalid

### ISSUE THREAD

**Issue by mark-summerfield** [JuliaEditorSupport/julia-vim#102]
I just did a fresh install of julia-vim & it fails to highlight first struct and wrongly marks final end as invalid (see attached). I'm using vim 7.4 on Ubuntu. Can't seem to attach so I've included the file here as code:

`module Dpl

struct PDF # JULIA-VIM BUG: not highlighted
    dpl::Int32
    pdf::Int32
end

end # module # JULIA-VIM BUG: highlighted as error
`

**Comment by carlobaldassi** [comment]
The plugin uses Julia 0.5 syntax highlighting by default, it will change when 0.6 will become the stable release. However, you can change the julia version, see [here](https://github.com/JuliaEditorSupport/julia-vim#changing-syntax-highlighting-depending-on-the-julia-version) for the short explanation or `:help julia-vim-version` for the complete one.

**Comment by mark-summerfield** [comment]
Thanks that solved the problem!
