### ISSUE TITLE
Spellchecking inside documentation

### ISSUE THREAD

**Issue by ronisbr** [JuliaEditorSupport/julia-vim#103]
Hi guys!

I use the following syntax in julia to document my functions:

```julia
"""
Documentation.
"""

function test()
    1+1
end
```

However, I am not able to spellcheck the words inside `""" ... """`. How can I do this?

**Comment by ronisbr** [comment]
I was using the following code to enable this:

```vim
" Set spell check for documentation.
augroup FileType_Julia
    autocmd FileType julia syntax region juliaTriString matchgroup=juliaStringDelim start=+"""+ skip=+\%(\\\\\)*\\"+ end=+"""+ contains=@juliaStringVars,@juliaSpecialChars,@Spell
augroup END
```

But, after a commit in the past days, this code is messing with the highlight syntax of the `""" ... """` block.

Without the code:

![captura de tela de 2017-03-08 16-04-28](https://cloud.githubusercontent.com/assets/1068295/23719137/ea6b7a7a-0418-11e7-9606-f47b6a6c6dd1.png)

With the code:

![captura de tela de 2017-03-08 16-03-58](https://cloud.githubusercontent.com/assets/1068295/23719122/da92031c-0418-11e7-8cbc-37172cd90c17.png)

**Comment by carlobaldassi** [comment]
It should work now, just remove your custom code.
Note: it only recognizes tri-strings that start at the first column, like in your examples (and like usual for docstrings).

**Comment by ronisbr** [comment]
Hi @carlobaldassi,

Excellent! It is working fine. How can I do if I also want spellchecking inside strings? Like:

```julia
println("This message should be checked.")
```

**Comment by carlobaldassi** [comment]
@ronisbr: I have just pushed another commit. You can now give the option `g:julia_spellcheck_strings=1` to achieve that. See the documentation with `:help julia-vim-options`.
