### ISSUE TITLE
"option 'omnifunc' is not set" with completers

### ISSUE THREAD

**Issue by ExpandingMan** [JuliaEditorSupport/julia-vim#105]
I believe this issue is similar to #25.  This happens using either YCM or [deoplete](https://github.com/Shougo/deoplete.nvim).  If I start editing a Julia file (I have to type some things in, not just open the file) and then switch to another Julia file without closing vim and start editing, the tab key no longer works for the purpose of creating normal tabs (it does work for auto-completion, but not LaTeX-to-Unicode, however automatic latex to unicode still works).  Instead of inserting a tab character or converting LaTeX to unicode I get the message `E764: Option 'omnifunc' is not set`.

This can be worked around by closing and re-opening vim every time I want to open a new file, which actually isn't *too* horrible, but it's growing increasingly annoying as I start to use tools like nerdtree somewhat more.  Certainly if I used vim tabs instead of tmux tabs it would be unworkable.

**Comment by carlobaldassi** [comment]
I occasionally get this too, and have yet to find the cause. However for the time being, as an improved workaround, rather than restarting vim, I suggest this mapping (or something similar) in your vimrc:

```
noremap <expr> <F7> LaTeXtoUnicode#Toggle()
inoremap <expr> <F7> LaTeXtoUnicode#Toggle()
```

This way, instead of restarting vim, you only need to press F7 twice and things should start working again.

**Comment by ExpandingMan** [comment]
Oh, I already had F7 mapped, but I didn't think of trying that, thanks!

**Comment by carlobaldassi** [comment]
Well, it seems to work for me now. Hopefully, I didn't break anything (it's hard to test all scenarios). Let me know.

**Comment by ExpandingMan** [comment]
So far seems to be working without any problems.  Thanks!
