### ISSUE TITLE
incorrect highlighting in abstract declarations in 0.6

### ISSUE THREAD

**Issue by ExpandingMan** [JuliaEditorSupport/julia-vim#107]
If one does, for instance
```julia
abstract type AbstractTest{T<:Number} end
```
Neither the `<:` nore the `Number` will get highlighted properly.  Oddly, this problem does *not* occur in `struct` or `mutable struct` declarations.

**Comment by ExpandingMan** [comment]
Wow do you fix things fast!  Thanks!

**Comment by carlobaldassi** [comment]
This one was easy :)
Thanks for reporting it.
