### ISSUE TITLE
multi-line function arguments don't indent properly as of fix to #106

### ISSUE THREAD

**Issue by ExpandingMan** [JuliaEditorSupport/julia-vim#109]
As of the fix to #106, if you start typing in a function definition (using a function block) and continue the argument list on multiple lines, there is some odd indenting behavior.  For example, if you do
```julia
function thisisafunction(arg1, arg2, ...
                                                arg3)
```
hitting enter at the ellipses you get an odd indent (though not quite as odd as you see above).  I'm pretty sure the correct behavior would be for the first argument on the second line to align with the first argument on the first line.

I don't know what the consensus would be, but speaking for myself, this is much more important to me than #106.

By the way, I use spaces instead of tabs, the following appear in my `init.vim`
```vim
set tabstop=4
set shiftwidth=4
" always use spaces instead of \t
set expandtab
set autoindent
set smarttab
```
in case that matters (I had the same settings before when I was getting the correct behavior).  (Admittedly I don't remember what the hell `smarttab` does at all.)

Thanks in advance!

**Comment by carlobaldassi** [comment]
I'm not able to reproduce this. I even tried with a nearly empty vimrc with just the julia-vim plugin and your options (plus a couple of standard settings like `set nocompatible` and `filetype plugin indent on`). For me, it correctly indents arg3 below arg1.
Do you have the latest version? I have no clue as to what may be happening.

**Comment by ExpandingMan** [comment]
Sorry!  I was slightly out of date.  For future reference, as of f4a8a780 I still have this problem, but as of the very latest commit 702bca672 it is fixed!  Thanks!
