### ISSUE TITLE
[Suggestion] Use iabbrev instead of imap for latex2unicode

### ISSUE THREAD

**Issue by ipod825** [JuliaEditorSupport/julia-vim#110]
First, I've encountered some problem with deoplete for latex2unicode provided by this plugin.
As I type words and deoplete shows completion menu, neovim then just get freezed.
I figured out that this issue is related to this line in ftdetect/julia.vim:
`autocmd InsertEnter *            let g:did_insert_enter = 1 | call LaTeXtoUnicode#Init(0)`.

After commenting out this line, everything just works fine (though the latex to unicode doesn't work then).

Currently, I've commented out that line and written a [plugin](https://github.com/ipod825/unilatex.vim/blob/master/plugin/unilatex.vim) (which I modify from unilatex.vim) for latex to unicode that works well with deoplete because I don't need to do any LaTeXtoUnicode#Init things.

The mechanism is to use iabbrev as follows:
```vim
let s:mapping={
\ '\alpha':'α', 
\ '\beta':'β',
}
for key in keys(s:mapping)
    let s:k = strpart(key, 1)
    execute 'inoreab '.s:k.' <c-r>=<sid>CheckSlash("'.s:k.'")<CR>'.s:mapping[key]
endfor                                                                                                          

function! s:CheckSlash(origin)
    if getline('.')[col('.')-2]=='\'
        return "\<bs>"
    else
        return a:origin
    endif
endfunction
```
Would it be possible to change the latex to unicode mechanism to this (seemingly) simpler method so that possible issue can be avoided?

**Comment by carlobaldassi** [comment]
I'll look into the `inoreab` suggestion.

About deoplete, what if instead you set this?
```vim
let g:latex_to_unicode_suggestions = 0
```
does it fix the problem?

**Comment by ipod825** [comment]
Yeah, that seems to solve the problem. Thanks for the tip.

**Comment by carlobaldassi** [comment]
I'll make it automatic if deoplete is detected then, just like for YouCompleteMe and neocomplete.

**Comment by carlobaldassi** [comment]
https://github.com/JuliaEditorSupport/julia-vim/commit/9c0054441350e434b6ce2851cf1962132440028d

**Comment by carlobaldassi** [comment]
It seems that the `inoreabbrev` mechanism doesn't work with mappings for things like `\^1` or `\_(` for example. This has to do with what is defined as a keyword in `iskeyword` and the rules for abbreviations when non-keyword characters are present (see `:help abbreviations`).

So even if this method is simpler and the `CheckSlash` trick helps with the leading backslash, I don't think it can be used as a substitute for the current code.

**Comment by ipod825** [comment]
That's fine. But (since I am still learning julia) when would \^1 be used? I typed in julia repl
```julia
x = 2
x\^2<Tab>
```
and get UndefVarError: x² not defined.

**Comment by carlobaldassi** [comment]
`\^2` doesn't do squaring, but you can use it as part of an identifier name, for example:
```
julia> χ² = 0.1
4.0

julia> a₍₀₎ = 2
2
```

**Comment by ipod825** [comment]
That's cool. I'll later check if I can use the same trick to check "^".

**Comment by carlobaldassi** [comment]
The main issue is that some abbreviations are only recognized according to these rules:

```
end-id	  In front of the match is a keyword character, or a space or a tab,
	  or this is where the line or insertion starts.

non-id	  In front of the match is a space, tab or the start of the line or
	  the insertion.
```

**Comment by ipod825** [comment]
I've changed to another method to make "^", "_" works. Though I am not sure if this method can be generalize to "complete as you type", but this works well with deoplete (and I guess also works for other completion plugin)

```vim
let s:mapping={
\ 'alpha':'α',
\ 'beta':'β',
\ '^1': '¹',
\ '_1': '₁'
\ }
function! g:CompleteLatex()
    let l:line = getline('.')
    let l:beg = strridx(l:line, '\')
    if l:beg==-1
        return
    endif
    let l:cur = col('.')-1
    let l:match = strpart(l:line, l:beg+1, l:cur-l:beg+1)
    if has_key(s:mapping, l:match)
        let l:pos = getpos('.')
        execute 's/\\'.l:match.'/'.s:mapping[l:match]
        call setpos('.', l:pos)
    else
        " dealing with characters behind match, e.g. \alpha|)
        let l:match = strpart(l:line, l:beg+1, l:cur-l:beg)
        if has_key(s:mapping, l:match)
            let l:pos = getpos('.')
            execute 's/\\'.l:match.'/'.s:mapping[l:match]
            call setpos('.', l:pos)
            normal h
        endif
    endif
endfunc

inoremap <Tab> <Esc>:call CompleteLatex()<Cr>a
```

Note that although mapping does not contain "\", you still need to type "\" to complete the keywords.

**Comment by carlobaldassi** [comment]
Doesn't the current code already work well with other completion plugins? I have just tried with neocomplete and auto substitution of LaTeX seems to work just fine.

**Comment by ipod825** [comment]
But don't you mention in README that it doesn't work well with neocomplete and other completion plugin? As what I've reported at the beginning is that I experienced freezing when using deoplete with Latex2Unicoe turned on. I thought that currently this plugin turned off Latex2Unicoe automatically when it detects some completion plugin?

By the way, the issue I reported still exists though I said it was solved. I just found that I can press <C-c> to get rid of the "freezing" and thought that the problem was solved. It must be something related to LaTeXtoUnicode#Init(), since even setting `let g:latex_to_unicode_suggestions = 0`. The autocmd `autocmd InsertEnter * let g:did_insert_enter = 1 | call LaTeXtoUnicode#Init(0)` is still executed in  ftdetect/julia.vim

**Comment by carlobaldassi** [comment]
At least with neocomplete, it's just the suggestions (the pop up menu) that conflict explicitly and which are disabled. Then there are likely some annoyances (I'm not sure, I don't use those plugins myself), but the autosub mechanism in particular should work ok.

I'll need to have a look at this freezing, since it just shouldn't happen. Could you post the portion of your configuration relative to deoplete?

**Comment by carlobaldassi** [comment]
I have just tried neovim (built from latest master) with deoplete, and everything seems to work. In particular, I observe no freezing, and the auto substitution of LaTeX to Unicode works. Could you post your `init.vim` file?

**Comment by ipod825** [comment]
I found that the real problem is a remapping of <Tab> for neosnippet and actually has nothing to to with deoplete. To reproduce the freezing, you need to type something that is not a latex command and press <Tab>, then your vim will get freezed, until you press <C-c>.
```vim
call plug#begin(s:vim_dir . 'bundle')
Plug 'Shougo/neosnippet'
call plug#end()

imap <expr><TAB> neosnippet#expandable_or_jumpable() ?
\ "\<Plug>(neosnippet_expand_or_jump)"
\: pumvisible() ? "\<C-n>" : "\<TAB>"

```

**Comment by carlobaldassi** [comment]
The problem there is that `<Tab>` is mapped recursively, and recursion is avoided only by an exception in vim mapping rules (see `:help recursive_mapping`). When I remap `<Tab>`, the exception does not take place anymore, and an infinite recursion occurs (the freezing that you observed).

In general this situation poses a hard to solve problem, but at least I fixed your case,
 I think (95d07dfdf3a10095b36155ceadbf72982c677924). Can you confirm?

**Comment by carlobaldassi** [comment]
P.S. I had to edit your comments to quote expressions like `<Tab>`, `<C-C>` etc., otherwise they don't appear in the text at all.

**Comment by ipod825** [comment]
Yes, that is fixed. Thanks. But I just found another issue. I will post another issue later.
