### ISSUE TITLE
L2U doesn't work with `set completeopt=noinsert`

### ISSUE THREAD

**Issue by ipod825** [JuliaEditorSupport/julia-vim#111]
When having `set completeopt=noinsert` in neovim. L2U doesn't work when pressing `<TAB>` (but L2U as you type works). This is the case without any completion & snippet plugins.

**Comment by carlobaldassi** [comment]
I just temporarily disabled that option while L2U is running, since it doesn't make sense otherwise. Also note that according to the documentation this option
```
Only works in combination with "menu" or "menuone". No effect if "longest" is present.
```
