### ISSUE TITLE
Handling of macros in comprehensions

### ISSUE THREAD

**Issue by bkamins** [JuliaEditorSupport/julia-vim#112]
When macros are used in comprehensions with no-parenthesis style the code is incorrectly highlighted and indentation is not correct. Example problematic statements:

![image](https://cloud.githubusercontent.com/assets/6187170/25899465/447f9232-3590-11e7-8054-fdadeba7aa4f.png)

Unfortunately I could not come up with the fix.

**Comment by carlobaldassi** [comment]
I did not fix it perfectly but the problems that the fix creates are less frequent than this one I think.

**Comment by bkamins** [comment]
@carlobaldassi Thank you!
