### ISSUE TITLE
feature request: switching between function declaration forms

### ISSUE THREAD

**Issue by ExpandingMan** [JuliaEditorSupport/julia-vim#113]
I have a relatively elaborate feature request (I feel a little silly asking for it rather than doing it myself, but I'm so unfamiliar with vim-script, and maybe it's something lots of other people want).  I'm a real stickler for the length of my lines: I usually have exactly 1 vertical split in vim, and I don't like my lines to go past it.  Therefore, I frequently find myself writing a function declaration like the following
```julia
f(x) = g(x)
```
but then realize that my function is too long, so I have to switch to
```julia
function f(x)
    g(x)
end
```
It would be really cool if there were a vim macro for switching between these.  This would be trivial to implement in Julia itself, but I'm not sure how to implement it in vim.

Does anyone else have this problem?  Would this be simple to implement?

**Comment by carlobaldassi** [comment]
Well, seemed like a good idea to me anyway. See `:help julia-vim-extras` (and report bugs if any).

**Comment by ExpandingMan** [comment]
That's absolutely *awesome* thanks so much!!  I haven't had much of a chance to check it out yet, but if I encounter any bugs I'll let you know.  I'll use this pretty much *all the time*, so this is quite exciting!
