### ISSUE TITLE
unicode character accents don't appear

### ISSUE THREAD

**Issue by ExpandingMan** [JuliaEditorSupport/julia-vim#115]
This may be a problem with my particular setup, but I am no longer able to do, for example `m\hat `.  Instead, the `\hat` disappears altogether and I wind up with a normal `m`.  Can anyone confirm this?  I suspect this *may* have broke with a neovim update, so I'm far from sure this is a julia-vim problem.

**Comment by carlobaldassi** [comment]
I have just tried with the latest neovim version pulled from github and it works fine for me. (With vim and gnome-vim as well).

In my experience, these things are sometimes dependent on both the terminal and the font however. I'm using gnome-terminal with DejaVu Sans Mono.

Here's the neovim version info:

```
$ nvim --version
NVIM v0.2.1-4042-g631d55a
Build type: Debug
Compilation: /usr/bin/cc -Wconversion -DNVIM_MSGPACK_HAS_FLOAT32 -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/home/carlo/Programs/neovim/build/config -I/home/carlo/Programs/neovim/src -I/home/carlo/Programs/neovim/.deps/usr/include -I/home/carlo/Programs/neovim/.deps/usr/include -I/home/carlo/Programs/neovim/.deps/usr/include -I/home/carlo/Programs/neovim/.deps/usr/include -I/home/carlo/Programs/neovim/.deps/usr/include -I/home/carlo/Programs/neovim/.deps/usr/include -I/usr/include -I/home/carlo/Programs/neovim/build/src/nvim/auto -I/home/carlo/Programs/neovim/build/include
Compiled by carlo@c-box-asus

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui      
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/home/carlo/local/share/nvim"
```

**Comment by ExpandingMan** [comment]
Hm, I'm not sure what changed.  I'm still using gnome-terminal with Ubuntu-Mono.  

Actually, come to think of it, I just switched away from Unity to GNOME desktop.  I wonder if that could have affected it.

Anyway, thanks.  Since I'm pretty confident this is not a julia-vim issue, I'll close this issue.
