### ISSUE TITLE
`?` as a unary operator screws up delimiters

### ISSUE THREAD

**Issue by ExpandingMan** [JuliaEditorSupport/julia-vim#116]
`?` can be used as a unary operator.  I'm not 100% sure when this feature was added, but it is starting to be used in the data ecosystem (see [Nulls.jl](https://github.com/JuliaData/Nulls.jl)).  Anyway, currently using `?` this way totally screws up delimiters, presumably because julia-vim expects `?` to be a ternary operator.  If it helps, ternary operators without spaces are very likely to eventually be [deprecated](https://github.com/JuliaLang/julia/issues/22025), and it seems like really bad practice anyway, so if it made things easier to not recognize ternary operators without spaces, I suspect that wouldn't be such a bad thing.

**Comment by carlobaldassi** [comment]
https://github.com/JuliaData/Nulls.jl/issues/17

**Comment by ExpandingMan** [comment]
See responses [here](https://discourse.julialang.org/t/announcement-an-update-on-dataframes-future-plans/4646/12).  Is there some kind of temporary, perhaps hackish and bad workaround for this?

**Comment by ExpandingMan** [comment]
Thanks so much!  That would have turned into a big pain!

**Comment by carlobaldassi** [comment]
Note that with this change spaces are required on both sides of `?` when it's used as a ternary operator. Which is not what the julia parser does, but anyway it's a decent compromise I think.
