### ISSUE TITLE
`include` and `define` options are not set as intended

### ISSUE THREAD

**Issue by gentbajraj** [JuliaEditorSupport/julia-vim#117]
Hi,
I don't understand vimscript very well but it seems to me that the `include` and `define` options are not being set as intended. I found the following lines [here](https://github.com/JuliaEditorSupport/julia-vim/blob/master/ftplugin/julia.vim):
```
setlocal include="^\s*\%(reload\|include\)\>"
...
setlocal define="^\s*macro\>"
```
However, whenever I'm in .jl file, the values of `include` and `define` are set to the default of vim. The following appears to work:
```
setlocal include=^\\s*\\(reload\\\|include\\\)\\>
...
setlocal define=^\\s*macro\\>
```
or alternatively,
```
let &l:include='^\s*\%(reload\|include\)\>'
...
let &l:define='^\s*macro\>'
```
Is this correct or I am doing something wrong?

**Comment by carlobaldassi** [comment]
You are right, thanks.
