### ISSUE TITLE
Similar problem to #36

### ISSUE THREAD

**Issue by epwalsh** [JuliaEditorSupport/julia-vim#118]
I am seeing a problem with the indentation similar to what was described in [#36](https://github.com/JuliaEditorSupport/julia-vim/issues/36). The indentation appears to be weirdly using TWO tab characters. I also tried putting this in my `.vimrc` in order to get 4 spaces to replace the tabs:

```vim
augroup filetype_julia
    autocmd!
    au BufRead,BufNewFile *.jl setlocal shiftwidth=4 expandtab
augroup END
```

but this doesn't work, i.e. Julia files are still indenting with two actual tab characters. In fact, the only way I can get it to behave the way I want is to manually enter `:setlocal shiftwidth=4 expandtab` after opening a Julia file.

**Comment by carlobaldassi** [comment]
This must somehow be related to your configuration. Can you post your vimrc?

**Comment by epwalsh** [comment]
(Using neovim by the way)

I was able to trace to the issue to the fact that I had a file in my `ftplugin` directory for Julia, `julia.vim`:

```vim
autocmd BufNewFile,BufRead *.jl set ft=julia
```

When I remove this file, everything works as expected. I guess we can close this then?

**Comment by carlobaldassi** [comment]
Well, I still don't know what went wrong here, and what went right when it got fixed, but I guess there's not really much to be done here.
