### ISSUE TITLE
Type definitions are not properly highlighted after `module`

### ISSUE THREAD

**Issue by ararslan** [JuliaEditorSupport/julia-vim#119]
![screen shot 2017-07-30 at 1 45 08 pm](https://user-images.githubusercontent.com/6396159/28756924-65ac0058-752d-11e7-93ea-aaf96b4536bd.png)

The same applies to `struct`

**Comment by carlobaldassi** [comment]
You probably have some line like

```vim
let g:default_julia_version = "0.5"
```

in your vimrc. If you set it to "0.6" or "0.7", or just remove it, it will work.
(It didn't work with 0.7, I just fixed it.)

Same goes for #120.

**Comment by ararslan** [comment]
Nope, I have it set to `"devel"`

**Comment by ararslan** [comment]
(which explains why it wasn't working for me, since it wasn't working with 0.7 🙂)
