### ISSUE TITLE
[Feature Request] auto complete of module functions?

### ISSUE THREAD

**Issue by jingpengw** [JuliaEditorSupport/julia-vim#125]
Maybe I am not using it correctly? Is there autocomplete of functions in a module?
let's say there is a module 
```julia
module Foos 
function bar() end 
end 
```
when I type `Foos.`, there is a list of available functions pop out as choices.

**Comment by ararslan** [comment]
I think that's out of scope for this plugin, which implements syntax highlighting and file recognition. You could check out the Julia integration with deoplete to see if that has what you're after.

**Comment by jingpengw** [comment]
ok, that make sense. close here.
