### ISSUE TITLE
unicode markings don't show up in column 1

### ISSUE THREAD

**Issue by ExpandingMan** [JuliaEditorSupport/julia-vim#129]
When using LaTeX to unicode, sometimes annotation markings such as hats and tildes don't show up (for example when doing `x\hat` or `x\tilde`).  Instead the `\tilde` will disappear and I'll be left with the original character without a marking.  I've actually been experiencing this for a while but didn't report it because I had no idea what was causing it (could have had something to do with neovim, tmux or even gnome-terminal).  Today however, I notice that I only have this problem only in column 1.  So, if I type in an indented block, or anywhere else on the screen other than the very first column, it seems to work fine.  Any chance that this is a julia-vim problem?  Can anyone reproduce it?

**Comment by carlobaldassi** [comment]
For me it works fine in all the settings that I tried (I used `gvim`, `vim` inside `gnome-terminal`, `vim` inside `tmux` inside `gnome-terminal`). I don't have neovim installed right now.

I have had occasional problems with these kind of characters in the past (although not limited to the first column), which I had solved by changing the font. Maybe try that?

**Comment by ExpandingMan** [comment]
Yeah, it might be the font, thing is, I'm really attached to this one (which is surprising, since it's just Ubuntu Mono, but it looks really nice and even has relatively good unicode... though I'd like to swap out the \chi and \nu characters which look like x and v).

Anyway, if you're not seeing this than I think it's highly unlikely that this is a julia-vim problem so I'll close this issue.  Perhaps it's neovim.

**Comment by carlobaldassi** [comment]
FWIW I'm also using Ubuntu Mono in the terminal (but in gvim I'm using DejaVu Sans Mono Book, which you may want to look into as it renders \chi and \nu much better).

**Comment by ExpandingMan** [comment]
Thanks I'll try that.  In my experience it's a pretty mixed bag; for example some other fonts might render \chi properly but not \mu (which Ubuntu Mono gets right).  Also fonts vary in how close they get to maintaining monospacing for unicode.  What I'd really like to do at some point is to just take Ubuntu Mono and swap in all of the best unicode characters I can find, but I haven't gotten around to it yet.
