### ISSUE TITLE
Variable name contains keyword

### ISSUE THREAD

**Issue by thofma** [JuliaEditorSupport/julia-vim#130]
First of all thanks for your great work. I noticed that if variable names contain keywords, the highlighting and indentation get's messed up. An example would be `work_type = 1` or `blub_if = 2`. Unfortunately I don't know enough vim fu to fix it myself.

**Comment by carlobaldassi** [comment]
I'm not able to reproduce this (and it shouldn't happen according to the syntax file regular expressions). Could it be something related to your configuration?

**Comment by thofma** [comment]
I don't know why, but I had `"set iskeyword-=_` in my vimrc. Removing this fixed it. Thanks!
