### ISSUE TITLE
Highlighting is wried on `while`

### ISSUE THREAD

**Issue by iblis17** [JuliaEditorSupport/julia-vim#138]
```julia
function f()
  while(true == false)
    continue
  end
end
```
![screenshot from 2018-02-08 18-50-35](https://user-images.githubusercontent.com/761623/35969186-fad01b4a-0d00-11e8-8ed2-337c0ee79080.png)

**Comment by carlobaldassi** [comment]
I can't reproduce this, it looks normal for me.
It looks like `while` is not being recognized as a keyword.
I have a hard time figuring out how this could happen at all.
Maybe some other conflicting plugin installed? Or some configuration option?
Can you provide more information, e.g. the vim version, your vimrc, etc.?

**Comment by mbaz** [comment]
Works for me, too.

**Comment by iblis17** [comment]
weird, on another machine. It renders fine. Sorry for this noise.
