### ISSUE TITLE
Feature request: Recognize ifelse as syntax

### ISSUE THREAD

**Issue by una-dinosauria** [JuliaEditorSupport/julia-vim#142]
[`ifelse`](https://docs.julialang.org/en/stable/stdlib/base/#Base.ifelse) is a handy construct in Julia.

Currently, julia-vim seems to recognize only the `if` part, and highlights subsequent `end`s as syntax errors. It would be nice to recognize `ifelse` as a function of its own.

**Comment by una-dinosauria** [comment]
Oh pardon me, the part about recognizing only the `if` part is not true.

It would still be nice to highlight `ifelse`.

**Comment by carlobaldassi** [comment]
`ifelse` is not syntax, it's a function. We don't highlight functions, generally. I don't think this should be an exception.

**Comment by una-dinosauria** [comment]
Fair point. Thanks a lot for your response.
