### ISSUE TITLE
some latex autocompletion (bbR) not working

### ISSUE THREAD

**Issue by piever** [JuliaEditorSupport/julia-vim#158]
I'm not sure if this is an issue with this package or if it comes from elsewhere, but some autocompletions that work in the REPL don't seem to work in Julia vim (I'm on neovim and Julia 1.0).

In particular `\bbR` (to give the `\mathbb{R}` LaTeX symbol) works in the REPL but not in Julia vim. Any idea what that could be?

**Comment by carlobaldassi** [comment]
I think you need to update the plugin, that family of characters was changed recently (used to be `\mathbbR` if I remember correctly).

**Comment by piever** [comment]
Should have updated before filing an issue, sorry about the noise. This fixed it, thanks for the quick reply!
