### ISSUE TITLE
Hitting <Tab> deletes single character before cursor, or whole Latex command

### ISSUE THREAD

**Issue by ThoAppelsin** [JuliaEditorSupport/julia-vim#164]
I am using Neovim v0.3.1 on Windows 10.1803. The problem in title persists even after I changed my `init.vim` to the following:

```vim
call plug#begin('~/AppData/Local/nvim/plugged')
" commented-out
Plug 'JuliaEditorSupport/julia-vim'
call plug#end()

" commented-out
```

I lose the whole Latex command without any Unicode replacements when I hit the tab key with my cursor right after a Latex command in INSERT mode. For example, `\alpha<Tab>` in Neovim in INSERT mode turns into nothing as soon as I hit the tab key, as if I hadn't typed anything.

More importantly, typing anything like `a<Tab>`, where `a` anything but not the last letter of a Latex command, also results in deletion of the character `a`. For example, if I am at the end of a line like `This is a line of text` with my cursor in INSERT mode, and were to hit tab key, I lose the last letter and have `This is a line of tex` instead.

Not having Latex command conversion is OK, since it has a good if not better workaround (`:let g:latex_to_unicode_auto = 1`). Hitting the tab key to simply insert a tab character but losing your last character is kind of annoying, and the `<C-v><Tab>` workaround is not so good (3 key presses instead of just one) hence it is also hard to learn.

**Comment by carlobaldassi** [comment]
Thanks for the report.
Can you try removing the `\b` from [this line](https://github.com/JuliaEditorSupport/julia-vim/blob/934618a71bcf64ff0fb94780dc1aefa58e81470a/autoload/LaTeXtoUnicode.vim#L80)?
Also, can you experiment with vim too?
If that works, we may need to revise the platform-specific code around it, maybe adapting it to neovim.

**Comment by ThoAppelsin** [comment]
Sorry, it took a while to install and configure Vim.

- I don't know if I got you right with "removing the `\b`", but I added `let s:l2u_esc_sequence = "\u0006"` at the end of my `init.vim` configuration file for Neovim. That didn't fix it, issue was still the same.
- I tried it with Vim, and it was still not working.
- I tried adding the same line to my `vimrc` configuration file for Vim, and it was still not working.

If you had wanted me to do something else than adding that line to the configuration files, then I need more info on how to.

**Comment by carlobaldassi** [comment]
Ah sorry. I meant editing the file `autoload/LaTeXtoUnicode.vim` on your computer, line 80, where your plugin manager has installed it. I suppose for nvim it's someghing like `/AppData/Local/nvim/plugged/autoload/LaTeXtoUnicode.vim` in your home.

**Comment by ThoAppelsin** [comment]
Wow, great! It works! It was under `[…]/plugged/julia-vim/autoload/[…]` or something, but yeah, removing `\b` did it! `\alpha<Tab>` turns into `α`, and my tabs now don't delete letters but simply insert the tab character. 

Is there any way I can help to get this solved in general?

**Comment by carlobaldassi** [comment]
Ok great. Now the problem is figuring out what's special about your configuration, if anything. The current code was a result of some trial and error tests (see #47). Unfortunately, I don't currently have access to a Windows machine.

**Comment by carlobaldassi** [comment]
I could run some tests on a Windows machine, with both vim and neovim, and both GUI can CLI versions, and in fact I couldn't find any case where the `\b` was useful rather than harmful. So I pushed a fix that just removes it.
