### ISSUE TITLE
Latex-to-Unicode doesn't work on Windows/Neovim on command-line with `<S-Tab>`

### ISSUE THREAD

**Issue by ThoAppelsin** [JuliaEditorSupport/julia-vim#165]
I am using Neovim v0.3.1 on Windows 10.1803. I had my `LaTeXtoUnicode.vim` modified in regards to the fix #164. This issue is present regardless of the modification, i.e. I tried it both with and without the modification.

The issue is simply that I cannot get L2U (Latex-to-Unicode) transformations on my Neovim's command-line, using the shift-tab key binding. When I use the `<S-Tab>`, I get the [horizontal tab control character `^I`](https://en.wikipedia.org/wiki/Control_character#In_ASCII) appended to the command, rather than getting it transformed. For example, `/\cup<S-Tab>` results in `/\cup^I`.

I'm new to Vim and I don't know why the default binding for transformation in command-line is `<S-Tab>` and not just `<Tab>`. However, I have found out that changing `<S-Tab>` on [**this line**](https://github.com/JuliaEditorSupport/julia-vim/blob/934618a71bcf64ff0fb94780dc1aefa58e81470a/autoload/LaTeXtoUnicode.vim#L464) to just `<Tab>`, changes the command-line L2U conversion key binding to just `<Tab>`, and then I can actually use the tab key to get my conversions on my Windows/Neovim perfectly fine.

Without the modification, this is an issue. Since you seem to have intentionally set the key binding as shift-tab instead of tab, maybe setting it to tab is not a good workaround, either.

**Comment by carlobaldassi** [comment]
If I remember correctly, the reason for not using just <kbd>Tab</kbd> in command line mode is that it overrides the standard vim command completion, and there's no way get it as a fall-back the way it can be done in insert mode.

Does it work if you change the binding to `C-Tab`?

**Comment by ThoAppelsin** [comment]
> standard vim command completion

Yeah, I totally forgot about that one. I am not sure which one I prefer having anymore... And sadly, changing it to `<C-Tab>` also doesn't work. However, `<C-l>`, and probably some others, does work!

I realized that changing [line 501 on this version](https://github.com/JuliaEditorSupport/julia-vim/blob/934618a71bcf64ff0fb94780dc1aefa58e81470a/autoload/LaTeXtoUnicode.vim#L501) is also necessary, at least to not get the error saying something like "no such key binding was found" on your first time entering the INSERT mode after opening a `*.jl` file.

`<S-Tab>` or `<C-Tab>` would be better, since they closely resemble the `<Tab>` counterpart in INSERT mode, but I guess it's not possible, but why? Is it Windows/PowerShell/Neovim? I just tried with everything but Julia-Vim and persistent undo lines commented out in my `init.vim`, and both `<S-Tab>` and `<C-Tab>` doesn't work like that either.

I can live with `<C-l>` for now, or even forever. If this is not somehow very specific to me, we may still call it an issue.

**Comment by carlobaldassi** [comment]
It occurred to me that adding a fallback was possible with a trick even in command mode, so now I have changed the default to <kbd>Tab</kbd>. It's still possible to use <kbd>S-Tab</kbd>, plus it's also possible to customize the mapping now if needed (explained in the documentation). Hope everything works as it should.
