### ISSUE TITLE
Misinterpretation of `obj.quote` as keyword

### ISSUE THREAD

**Issue by Jasha10** [JuliaEditorSupport/julia-vim#168]
Syntax highlighting is messed up by the following line of code:
```["$(obj.base)/$(obj.quote)" for obj in eachrow(edgelist[[:base,:quote]])]```
Here `obj.quote` is just some field of the `obj` object, but julia-vim is interpreting the word `quote` as a keyword. This causes the entire document (starting with the word ` for` in the above line of code) to be highlighted as if it were a string.

**Comment by Jasha10** [comment]
Sorry, why was this closed?

**Comment by carlobaldassi** [comment]
It's supposedly fixed now.
