### ISSUE TITLE
E59: invalid character after \@

### ISSUE THREAD

**Issue by biofuture** [JuliaEditorSupport/julia-vim#170]
"resistome_host.jl" 59L, 877C
Error detected while processing /home/.vim/syntax/julia.vim:
line  161:
E59: invalid character after \@
E475: Invalid argument: juliaKeyword^I^Idisplay "\%(\.\)\@1<!\<\%(return\|local\|global\|import\%(all\)\?\|export\|using\|const\|where\)\>"
line  163:
E59: invalid character after \@
E475: Invalid argument: juliaRepKeyword^I^Idisplay "\%(\.\)\@1<!\<\%(break\|continue\)\>"
line  164:
E59: invalid character after \@
E475: Invalid argument: juliaConditionalBlock^Imatchgroup=juliaConditional start="\%(\.\)\@1<!\<if\>" end="\%(\.\)\@1<!\<end\>" contains=@juliaExpressions,juliaConditionalEIBlock,juliaConditionalEBlock fold
line  165:
E59: invalid character after \@
E475: Invalid argument: juliaConditionalEIBlock^Imatchgroup=juliaConditional transparent contained start="\%(\.\)\@1<!\<elseif\>" end="\%(\.\)\@1<!\<\%(end\|else\|elseif\)\>"me=s-1 contains=@juliaExpressions,juliaConditionalEIBlock,juliaConditionalEBlock
line  166:
E59: invalid character after \@
E475: Invalid argument: juliaConditionalEBlock^Imatchgroup=juliaConditional transparent contained start="\%(\.\)\@1<!\<else\>" end="\%(\.\)\@1<!\<end\>"me=s-1 contains=@juliaExpressions
line  167:
E59: invalid character after \@
E475: Invalid argument: juliaWhileBlock^I^Imatchgroup=juliaRepeat start="\%(\.\)\@1<!\<while\>" end="\%(\.\)\@1<!\<end\>" contains=@juliaExpressions fold
line  168:
E59: invalid character after \@
E475: Invalid argument: juliaForBlock^I^Imatchgroup=juliaRepeat start="\%(\.\)\@1<!\<for\>" end="\%(\.\)\@1<!\<end\>" contains=@juliaExpressions,juliaOuter fold
line  169:

**Comment by carlobaldassi** [comment]
Do you have the latest version of the plugin? This should have been fixed in the latest commit.

**Comment by carlobaldassi** [comment]
Due to lack of activity I'm assuming this issue fixed.
