### ISSUE TITLE
Feature request: fold multiline comments

### ISSUE THREAD

**Issue by alhirzel** [JuliaEditorSupport/julia-vim#171]
It would be nice to be able to fold [multiline comments](https://docs.julialang.org/en/v1/base/punctuation/index.html) such as the following:

```julia
println("code code code")

#=
# Verb the noun (DISABLED FOR NOW)
...
=#

println("code code code")
```

**Comment by avigliotti** [comment]
this feature works weel with GVim on windows, but it does not seem to work with GVim on Linux (Kubuntu), is there anything I can do or check?
