### ISSUE TITLE
Pick up non-base types as types

### ISSUE THREAD

**Issue by Donkeyfish87** [JuliaEditorSupport/julia-vim#173]
julia-vim doesn't pick up types in a syntax group if the type is custom, e.g. `::DataFrame`.

It would be nice if possible to include this as well, at least for the types coming from the most used packages (that follows naming conventions).

**Comment by Donkeyfish87** [comment]
This should be possible to catch with a regex like `"\v::\zs\w*\ze"`

But I'm having problems getting it to work, same issue as I described in #172

**Comment by m-wells** [comment]
I'm confused.  Vim is not using `::` to determine types. [`::` is defined as an operator](https://github.com/JuliaEditorSupport/julia-vim/blob/84104d0d55db347be045927e71cf9b0a88e72c2f/syntax/julia.vim#L85).  The types are explicitly defined [here](https://github.com/JuliaEditorSupport/julia-vim/blob/84104d0d55db347be045927e71cf9b0a88e72c2f/syntax/julia.vim#L198).

If you really wanted. You could [add to an existing syntax file](http://vimdoc.sourceforge.net/htmldoc/syntax.html) by creating `~/.vim/after/syntax/julia.vim` and putting something like
```vim
syn match DataFrameTypes "\<\%\(DataFrame\|DataFrameRow\)\>"
hi def link DataFrameTypes Type
```
into it.
(I only include `DataFrame` and `DataFrameRow` but you could implement them all).
If you don't like you could also make these `autocmd`s in your `.vimrc`
```vim
if has("autocmd")
augroup julia_syntax_custom
  au!
  autocmd Syntax julia syn match DataFrameTypes "\<DataFrame\>"
  autocmd Syntax julia hi def link DataFrameTypes Type
augroup END
endif
```
either way.  This isn't something that should go into the base `julia-vim` syntax file as it is not apart of the `julia` language.

**Comment by m-wells** [comment]
[You might also want to look into syntax highlight using tags.](https://github.com/xolox/vim-easytags)

**Comment by Donkeyfish87** [comment]
Yes that's true, it would pick up non-defined types. That's the way it's done in Juno and Sublime text, everything after :: is colored as a type. Which makes it easier to read I think, especially when you have say three arguments that are Int, Bool and DataFrame or similar.

**Comment by Donkeyfish87** [comment]
Ah taghighlight might be a clever solution, as that can pick up structs.

**Comment by m-wells** [comment]
> Yes that's true, it would pick up non-defined types. That's the way it's done in Juno and Sublime text, everything after :: is colored as a type. Which makes it easier to read I think, especially when you have say three arguments that are Int, Bool and DataFrame or similar.

I understand your point in terms of readability but I think it is much safer to highlight on the matching of the types themselvels. For instance in this case
```julia
using DataFrames
df = DataFrame()
isa(df, DataFrame)
```
`DataFrame` wouldn't be highlighted because there isn't an `::` operator.  Github is highlighting it in line 2 because it thinks it is a function
```julia
zeros(5)
```

> Ah taghighlight might be a clever solution, as that can pick up structs.

To extend upon this, you can have something like [vim-gutentags](https://github.com/ludovicchabant/vim-gutentags) generate a tags file for any project you work on.

**Comment by Donkeyfish87** [comment]
You make good points. That would be another inconsistency, which might be just as or more annoying. DataFrame being highlighted one place but not another yet both places meaning the same.

I failed to consider all the implications. On reflection I'm starting to lean your way.
