### ISSUE TITLE
julia-vim breaks completion with Tab/S-Tab in vim command line

### ISSUE THREAD

**Issue by ikselven** [JuliaEditorSupport/julia-vim#174]
**Steps to reproduce:**
1. have julia-vim installed
2. open any *.jl file
3. press `:` to open vim command line
4. enter something, e.g. `set fold`
5. press `Tab` repeatedly

**Expected Behaviour:**
vim "scrolls" through all entries starting with `set fold`, i.e. `set foldclose`, `set foldcolumn`, `set foldenable` etc.

**Actual Behaviour:**
vim completes only the first possible entry, i.e. `set foldclose`, repeatedely pressing `Tab` does not change anything.

Using vim 8.1.1073 on Arch Linux, no additional configuration for julia-vim apart from 3 lines for additional syntax highlighting.

I've found that disabling `Tab` for L2U via `let g:latex_to_unicode_tab = 0` in my .vimrc fixes this problem and gives me the expected behaviour again.

I'm not sure, if this is just a limitation/drawback of having `Tab` key for L2U enabled or actually a bug.

**Comment by JohnEdChristensen** [comment]
I am experiencing the same issue. Disabling `latex_to_unicode_tab` does work, but I would like to still use this feature and maintain expected vim behavior. Is there anyway to remap tab for L2U?

**Comment by carlobaldassi** [comment]
You can change the mapping with the `g:latex_to_unicode_cmd_mapping` variable (you can look it up in the help).
For example,
```
let g:latex_to_unicode_cmd_mapping = ['<C-J>']
```
will let you use <kbd>CTRL-J</kbd>.

I wish I could find a way to fix this more properly.

**Comment by ikselven** [comment]
Thanks for pointing out this workaround.

**Comment by carlobaldassi** [comment]
Sorry, I thought I had found a workaround but it seems like it's neovim-specific, so I have reverted the commit. I'll reopen the issue...

**Comment by carlobaldassi** [comment]
Ok now this should be actually fixed in both vim and neovim.

**Comment by ikselven** [comment]
Thanks :)
