### ISSUE TITLE
julia can not auto-complete

### ISSUE THREAD

**Issue by Lyndonxie** [JuliaEditorSupport/julia-vim#175]
hope to add a function of atuo-complete

**Comment by m-wells** [comment]
What specific functionality are you looking for? There is the built in `omnifunc` (see `:help omnifunc`), [YouCompleteMe](https://github.com/Valloric/YouCompleteMe), [deoplete](https://github.com/Shougo/deoplete.nvim), [mucomplete](https://github.com/lifepillar/vim-mucomplete) and snippet plugins abound ([vim-snippets](https://github.com/honza/vim-snippets), [UltiSnips](https://github.com/SirVer/ultisnips), [snipMate](https://github.com/garbas/vim-snipmate)).
