### ISSUE TITLE
Having trouble with the repo.

### ISSUE THREAD

**Issue by sgbaird** [JuliaEditorSupport/julia-vim#176]
Followed the instructions listed for manual and vim-plug installation on 2 different networks. Is there a chance it's an issue with the repo?

**Comment by carlobaldassi** [comment]
What kind of trouble exactly?

**Comment by sgbaird** [comment]
Thank you for such a quick reply. I just tried doing :PlugInstall inside vim (I haven't personally changed anything else) and it worked, so I wasn't able to reproduce the error just now. When I did :PlugInstall it would usually just hang. When I tried doing it manually, it would basically just say failed to clone the repository. This is while being ssh'd into a campus supercomputer. I thought maybe it was a network issue and so tried a phone hotspot but same thing. Another time I think it said failed to connect to github. At any rate, I was able to install it.
