### ISSUE TITLE
:help julia-vim File name missing or invalid pattern

### ISSUE THREAD

**Issue by anandijain** [JuliaEditorSupport/julia-vim#179]
I installed via git clone (manual install). I have no other plug-ins and my ~/.vim/ looks  like:
```
~/.vim$ ls
autoload  ftdetect  indent      keymap      logo.png   syntax
doc       ftplugin  INSTALL.md  LICENSE.md  README.md
```
When I :help julia-vim within vim I get `File name missing or invalid pattern'.

I copied and pasted the commands for the install, so it was exactly as specified. I wondered if moving the repo files into a folder called julia-vim would work, but then when running `:help julia-vim' I get `E149: Sorry, no help for julia-vim`.

So I moved them out of the folder, but I think that the help is not working properly.
Thanks

**Comment by machakann** [comment]
It may be worth trying to type `:helptags {path-to-julia-vim}/doc`. Please substitute `{path-to-julia-vim}` to the appropriate path. I'm not sure your current situation but maybe `helptags ~/doc`?

...but I recommend to use any one of plugin managers.
