### ISSUE TITLE
julia vim with YouCompleteMe inserts extra tabs/spaces randomly

### ISSUE THREAD

**Issue by scottstanie** [JuliaEditorSupport/julia-vim#180]
This one is a little hard to reproduce, as it's not happening all the time. 
I've used YouCompleteMe for awhile, and they two generally play nice together when I'm editing files. But sometimes it do the following (recorded below)
Note that in the recording, i just type out the letters "int" and with no extra keys, it inserts a bunch of spaces.

Even weirder- when I exit insert mode, and then try and retype the same thing, no extra spaces are inserted.

Has anyone else seen this behavior? The erratic nature makes it hard to give a minimum reproducible example, but this happens decently often to me after coding for awhile.

Also I'll note that it's not even the same amount of spaces inserted every time- it can be anywhere from 2 to 4 extra spaces

![julia-vim-glitch](https://user-images.githubusercontent.com/8291800/63868479-342cf500-c97c-11e9-9b00-21f470568488.gif)

**Comment by javieryu** [comment]
Any updates on this issue? I am also experiencing this problem.

**Comment by carlobaldassi** [comment]
Hopefully, this is fixed in master now. At least in my tests it is.
If the problem persists, leave a comment and I'll reopen.
