### ISSUE TITLE
Generator expressions aren't recognised properly and break indentation

### ISSUE THREAD

**Issue by spaceLem** [JuliaEditorSupport/julia-vim#183]
I'm having issues with generator expressions such as
```julia
    x = (i for i in 1:10)
    y = sum(1/n for n in 1:10)
````
They don't seem to highlight properly, the closing `)` is highlighted as though it were an erroneous additional parenthesis.

Also, lines after the expression are indented, as though the `)` didn't exist and the extra indent level from the opening parenthesis `(` is still active. I've attached a screenshot to show what I mean (showing that I've just run `gg=G` to indent everything).

![Screenshot from 2019-11-27 18-01-25](https://user-images.githubusercontent.com/6231990/69748357-0ce2f100-1140-11ea-9d0a-4ee208e6d5c3.png)

**Comment by carlobaldassi** [comment]
Works fine for me. Do you have the latest version of the plugin?

**Comment by spaceLem** [comment]
I thought I did (julia-vim was installed by vim-plug, which claimed everything was up-to-date), but maybe it wasn't. I cleaned out my .vim directory and re-downloaded everything and it seems to be working now.
