### ISSUE TITLE
Highlighting of right-hand parenthesis with field-name "type"  

### ISSUE THREAD

**Issue by yakir12** [JuliaEditorSupport/julia-vim#185]
Is the highlighting of the right-hand parenthesis here intended?
![screenshot_2020-02-11_14:21:44](https://user-images.githubusercontent.com/3281957/74240271-e01f8e00-4cd9-11ea-8c30-8fd04f83e4c3.png)

**Comment by carlobaldassi** [comment]
It's motivated by the support for old julia versions in which `type` was a keyword. You can avoid it by  using `let g:default_julia_version = "devel"` in vimrc, or using the function `julia#set_syntax_version`. See `:help julia-vim-version`.

Very soon, I'll simply remove the support for deprecated julia versions and this won't be a problem any more.

**Comment by yakir12** [comment]
Awesome! Thanks. Closing this then :)

**Comment by carlobaldassi** [comment]
Small update: I have just removed the support for legacy Julia version, so setting the `g:default_julia_version` variable should be unnecessary if you update the plugin.

**Comment by yakir12** [comment]
I can confirm this to be true :)
