### ISSUE TITLE
Package is messing with indentation

### ISSUE THREAD

**Issue by cup** [JuliaEditorSupport/julia-vim#186]
With a `_gvimrc` like this:

~~~vim
packadd julia-vim-master
set expandtab
~~~

If I have a Julia file like this:

~~~jl
function f1(n1)
end
~~~

Pressing TAB inside the function creates 16 spaces. I dont want this package
doing anything with my indentation. I want it to highlight my files, thats it,
and leave any indentation to my global Vim settings. How do it tell this package
to stop changing my indentation settings?

**Comment by cup** [comment]
As a workaround:

1. Delete everything but `syntax` folder

2. Add `autocmd BufRead,BufNewFile *.jl set filetype=julia` to `_gvimrc`

Looks like the problem is here:

https://github.com/JuliaEditorSupport/julia-vim/blob/8c0b9e8f87091ff17abbca752fa30e3a34ebb5a1/ftdetect/julia.vim#L10-L22

I have no need for LaTex, so I think all that should be disabled by default.

**Comment by carlobaldassi** [comment]
Indentation and LaTeX-to-Unicode should be completely independent.
I don't understand the original issue. What do you mean exactly with this?

> Pressing TAB inside the function creates 16 spaces.

Where inside the function exaclty? I your example there is no "inside the function". Where is the cursor exactly? We're talking about insert mode right?
Also, whatever I do with your example I generally see that the Tab key produces 4 characters at most. Pressing Return after the function header in insert mode creates a new line with 4 spaces and the cursor right after that, and pressing Tab results in 4 more spaces. If you see 16 spaces, it's likely a bug.

If you provide (a lot) more details we can try to work it out. In any case LaTeX-to-Unicode can be disabled if you don't want it (see the documentation).

**Comment by cup** [comment]
Create a file `a.jl`. Then type `function f1(n1)` ENTER. It will indent 8
spaces, which is fine. But as an example, if you then delete those spaces, then
press TAB, it indents 16 spaces.

**Comment by carlobaldassi** [comment]
I can't reproduce this, everything works fine for me. Can you provide more info? Operating system (I'm assuming Windows? Which version?), vimrc file, vim version?
What happens if you add `let g:latex_to_unicode_tab=0` to vimrc?

**Comment by cup** [comment]
> Operating system (I'm assuming Windows? Which version?)

Windows 7

> vimrc file

See original comment

> vim version?

8.2.259

> What happens if you add `let g:latex_to_unicode_tab=0` to vimrc?

That fixes the problem. That should probably be disabled by default, as I think
more people just want Julia syntax highlighting and dont care about anything
related to LaTeX.

**Comment by carlobaldassi** [comment]
> That should probably be disabled by default

Not going to happen. Every other editor plugin for Julia files works like the Julia REPL and changes LaTeX to Unicode upon pressing Tab. Unicode symbols are extremely common in Julia code.

Unfortunately I don't have a Windows 7 machine to tests things right now.
Could you try experimenting with [this line](https://github.com/JuliaEditorSupport/julia-vim/blob/8c0b9e8f87091ff17abbca752fa30e3a34ebb5a1/autoload/LaTeXtoUnicode.vim#L83), perhaps adding a `\b` at the end of the string, and also tell whether you observe a difference between vim and gvim?

**Comment by cup** [comment]
I appreciate you helping me identify the issue, but I think the LaTeX should be disabled by default. So you can certainly understand that given my viewpoint, that I definitely dont want to troubleshoot something I dont want in the first place.

I will continue to use the `latex_to_unicode_tab` option, good luck to you in fixing the issue for people who keep it enabled.
