### ISSUE TITLE
wrong highlighting on new `a[begin:n]` functionality

### ISSUE THREAD

**Issue by piever** [JuliaEditorSupport/julia-vim#188]
In Julia 1.4 it is now possible to do `a[begin:2]` to get all entries of an array from the first index (which could be different from `1` in OffsetArrays) to the index `2` in this example.

However the syntax highlighting here reports it as an error (see screenshot)
![Screenshot from 2020-03-01 22-11-10](https://user-images.githubusercontent.com/6333339/75634929-d074d480-5c09-11ea-839c-21806eb538aa.png)

I'm on latest master of julia-vim. I've tried setting
```
let g:default_julia_version = "devel"
```
but that didn't help.

**Comment by carlobaldassi** [comment]
Thanks for the report. It should work now. This was surprisingly hard and annoying to fix. Hopefully, the fix doesn't introduce too much of a performance hit (it doesn't seem to on on my laptop, but it's yet one more expensive regex given to vim's syntax parser...)

**Comment by piever** [comment]
It seems to work fine on my machine as well. Thanks for such a quick fix!
