### ISSUE TITLE
`set paste` breaks latex-to-unicode

### ISSUE THREAD

**Issue by imLew** [JuliaEditorSupport/julia-vim#190]
In both neovim (0.5-nightly) and vim (8.2) using `set paste` breaks the julia vim suggestions and substitutions for latex to unicode.
Not sure how to get the version of the plug-in im using. `PlugSnapshot` tell me it is commit `8ea33c2` (latest as of this posting).

**Comment by carlobaldassi** [comment]
Well, `set paste` disables all mappings, abbreviations etc (see `help nopaste`), so I don't know if anything could be done at all about this. At least in neovim, the help states that `paste` is obsolete and that `bracketed-paste-mode` is built-in. In general, I don't think this option is intended to be on by default, and you can use `pastetoggle` to enable/disable it quickly when you need it.

**Comment by imLew** [comment]
Thanks for your reply. I didn't know `set paste` turns off mappings so I thought it might have been a bug.
