### ISSUE TITLE
% doesn't work with `@warn("foo do")`

### ISSUE THREAD

**Issue by bjarthur** [JuliaEditorSupport/julia-vim#196]
positioning cursor on `function` and pressing `%` does not move cursor to `end` in the first function below, but does in the next two.  :

```
function foo()
  @warn("foo do")
end

function foo()
  @warn("do")
end

function foo()
  @warn("foo")
end
```

**Comment by carlobaldassi** [comment]
Thanks, it should be fixed now. For the record, the problem here was the `do` appearing right after an expression like `@warn("foo` which was being incorrectly matched. Overall it was behaving as in the case `@somemacro do`, thus screwing up the matchit functionality.

**Comment by bjarthur** [comment]
thanks!

hard to add tests or just impossible?

**Comment by carlobaldassi** [comment]
Hard, for me at least. I'm not familiar at all with testing protocols for vim.
