### ISSUE TITLE
Highlight Julia's predefined functions

### ISSUE THREAD

**Issue by binarygcd** [JuliaEditorSupport/julia-vim#200]
Maybe this is too much but can you add highlighting for functions from Base and Stdlib? It helps if you want to avoid name conflict and distinguish more between your own and Julia's functions.

**Comment by carlobaldassi** [comment]
I don't think this is doable, I have left a few comments around with the reasoning, e.g.
https://github.com/JuliaEditorSupport/julia-vim/issues/24#issuecomment-382187518
https://github.com/JuliaEditorSupport/julia-vim/pull/235#issuecomment-787204645
https://github.com/JuliaEditorSupport/julia-vim/issues/226#issuecomment-787120113
