### ISSUE TITLE
Don't indent multiline strings

### ISSUE THREAD

**Issue by gustaphe** [JuliaEditorSupport/julia-vim#201]
Function documentation in multiline strings, like
```
"""
documentation
"""
function(...)
```
must preserve indentation. Both for clarity, but also because they can actually run as tests, which will fail if they are incorrectly indented. I think the indentation should simply skip multiline strings altogether.

**Comment by carlobaldassi** [comment]
Sorry, I don't understand. The example that you give gets indented exactly like that when I test it.
Can you provide a simple example of 1) what you type 2) what you expect 3) what you get instead?

**Comment by gustaphe** [comment]
Sure, sorry.

Buffer content:
```julia
"""
This is more advanced documentation
        It has manual indentation in it
"""
```
Running `gg=G` changes this to
```julia
"""
This is more advanced documentation
It has manual indentation in it
"""
```
I would expect it to leave the indentation intact.

**Comment by carlobaldassi** [comment]
Ok thanks. I think this should be fixed now, at least for docstrings.
