### ISSUE TITLE
Cursorline display bug for some symbols

### ISSUE THREAD

**Issue by CrunchyFlakes** [JuliaEditorSupport/julia-vim#202]
Hi everyone,

I get a highlighting bug when using the cursorline feature of vim. The area of around some symbols doesn't get highlighted as it should. Here a screenshot explaining the problem better than me:
![julia_vim_cursorline_bug](https://user-images.githubusercontent.com/26522466/88463265-cf428d80-ceb1-11ea-8d50-68134ec92d3b.png)

How to reproduce?
":set cursorline" and then type e.g. 'for i = 1:10'. Highlighting around "=" and ":" will be off.

Thanks
Malte Töpperwien

**Comment by m-wells** [comment]
Can you try to reproduce with a minimal `.vimrc`? I do not get this issue.
![2020-07-27-112639_3840x2160_scrot](https://user-images.githubusercontent.com/6752069/88560607-5a2f9f00-cffc-11ea-9ac9-ade6f36808a2.png)

**Comment by carlobaldassi** [comment]
My guess is that it's an issue with the colorscheme. Can you try to change colorscheme?

As for fixing, those items are highlighted as "Operator", so maybe you can try to modify the `hi Operator ...` line in your colorscheme.

**Comment by CrunchyFlakes** [comment]
@carlobaldassi Yes, you are right. Without the colorschmeme everything is fine. Sorry for the wrong alert!
