### ISSUE TITLE
Remove red highlighting for keywords used as properties

### ISSUE THREAD

**Issue by clarkevans** [JuliaEditorSupport/julia-vim#203]
In Julia, it is possible for keywords to be used as properties.  For example, one can use `end` as a property of a structure.  Currently, in the syntax highlighter, keywords used as properties are highlighted in *red* as if they are errors, yet they are not. \
In the example below, `end` is highlighted with red in the expression `foo.end`.  Yet, this works and is not an error.

```julia
struct Foo
end

function Base.getproperty(foo::Foo, name::Symbol)
    if name == :end
        return "This is the end."
    end
end

foo = Foo()

println(foo.end)
#-> This is the end.
```

At this time, it seems that Github's syntax highlighter also has this issue.

**Comment by carlobaldassi** [comment]
Thanks, should be fixed now.
