### ISSUE TITLE
Latex-to-Unicode on non-code filetypes inserts an extraneous control character

### ISSUE THREAD

**Issue by rabirabirara** [JuliaEditorSupport/julia-vim#204]
As the title says - in text filetypes, at the moment of insertion of a unicode symbol, an extra control character '^F' is also inserted into the buffer.  This occurs on both nvim-qt and terminal nvim.  

Text file:

![image](https://user-images.githubusercontent.com/59306451/91621447-f58f9900-e947-11ea-9f87-cfb78d6af70c.png)

Julia:

![image](https://user-images.githubusercontent.com/59306451/91621544-35568080-e948-11ea-9a4c-650ad5b54d8a.png)

I tested this with a minimal init.vim.  The problem still persists.

```Vim
" Using vim-plug.
call plug#begin()
Plug 'JuliaEditorSupport/julia-vim'
call plug#end()

let g:latex_to_unicode_file_types = ["julia", "text"]
```

*EDIT:* I neglected to test this with other programming languages, instead of just text/custom-defined filetypes.  The problem occurs in text; I tested it with Rust and it did not occur.

**EDIT 2:**  I inspected the plugin's code, and found this in autoload/LaTeXtoUnicode.vim, which may be the culprit. 

```Vim
" A hack to forcibly get out of completion mode: feed
  " this string with feedkeys()
  if has("win32") || has("win64")
    let s:l2u_esc_sequence = "\u0006"
  else
    let s:l2u_esc_sequence = "\u0091\b"
  end
```
Indeed, the code for the ^F control character is 06.  And as I forgot to mention, I am using Windows 10.

***EDIT:*** It turns out when editing text filetypes, julia-vim overall inserts the control character whenever you press Tab.  I looked in the code, and for text files, all three occurences of `call feedkeys(s:l2u_esc_sequence, 'n')` cause ^F to be inserted into the text file - when a completion is not found, when a completion is perfectly found, and when a completion is partially found.

This is a text file I used to test it, with the same minimal init.vim:

![image](https://user-images.githubusercontent.com/59306451/91622997-88333680-e94e-11ea-80b9-36aa819e53d8.png)

I'm not exactly competent at writing vimscript, but I'll look into the issue further.

**Comment by carlobaldassi** [comment]
I have no clue why the behavior should be any different between text or non-text files, this is very strange. Unfortunately, I have no Windows machine on which to test this. Does the problem go away if you change `"\u0006"` to `"\u0006\b"` in the code? And if so, does it then break the non-text files? Also, just for completeness sake, could you just use `latex_to_unicode_file_types = ".*"` and try a few other file types, just with `:set ft=python` or `cpp` or `tex` etc for example, and see if it's really just text files?

**Comment by rabirabirara** [comment]
Yes; I had gone into LaTeXToUnicode.vim and added a buffer variable with that escape sequence and had julia-vim match the filetype of the buffer with a global list of filetypes that required this special sequence.  It all works out.

As for testing other filetypes, I think two distinctions are to be made: custom file types one defines in ftdetect, or unknown filetypes, and of course text introduce this behavior.

The behavior doesn't occur when using Julia, Rust, Python, C, Markdown.  I'd wager it doesn't occur with any programming language, certainly not any built

I have a custom defined filetype .jn I use to take notes; it occurs there.  Audacity has a .lof filetype that it uses to notate batch opening of files (which Vim doesn't recognize, and perceives as having no filetype); it occurs there.  And of course, it occurs in .txt.

I tested .tex - that is, ft=plaintex - and it occurred there:

![image](https://user-images.githubusercontent.com/59306451/91640240-ec96da00-e9d0-11ea-895a-553a0d478ead.png)

However, as soon as I set the filetype to something like, say, Go, the control characters stop inserting.  The pic may be a little unclear; what I did immediately after the last pic was :set ft=go and type in some L2U.  To clarify the presence of Go I noted the go-pls initialization in messages.

![image](https://user-images.githubusercontent.com/59306451/91640298-5e6f2380-e9d1-11ea-9017-2e1e8fe8c5e5.png)

**Comment by rabirabirara** [comment]
To be more specific about how I made my hack workaround, I tried several escape sequences, with different control characters; most control codes other than \u0006 did not appear (some did).  However, other crazy behavior was introduced with them; so I didn't pursue their usage any further.

In init.vim, I have:

```Vim
let g:latex_to_unicode_file_types = ".*"

" A hack fix for extraneous control character insertions.
let g:latex_to_unicode_file_types_backspace = ["text", "etc."]
```
and in LaTeXToUnicode.vim, I added:
```Vim
if has("win32") || has("win64")
    let s:l2u_esc_sequence = "\u0006"
    let s:l2u_esc_sequence_backspace = "\u0006\b"
```
...in the function LaTeXToUnicode#Refresh(), I appended this:
```Vim
" My hack.
  if match(g:latex_to_unicode_file_types_backspace, &ft) > 0
	let b:l2u_esc_bs = 1
  else
	let b:l2u_esc_bs = 0
  endif
```
...and in each occurence of feedkeys that fed the escape sequence, at around lines 280, 330, 350, and later on in AutoSub(), I added an if statement like the following:
```Vim
if b:l2u_esc_bs == 1
     call feedkeys(s:l2u_esc_sequence_backspace, 'n')
else
    call feedkeys(s:l2u_esc_sequence, 'n')
endif
```

In all, this works for me.  As for why this behavior occurs on Windows 10, in both Gui and terminal, and on these certain file types, I have no clue, unfortunately.

**Comment by rabirabirara** [comment]
@carlobaldassi It works! On both kinds of filetypes (code and text files alike). Thank you so much for this.
