### ISSUE TITLE
Pressing <Tab> after only whitespce strips all whitespace before inputting the tab

### ISSUE THREAD

**Issue by rabirabirara** [JuliaEditorSupport/julia-vim#205]
While investigating an earlier issue I submitted, I found what I believe is another bug (or I will look stupid if it's my own fault!).

In both gui and terminal Neovim, when pressing Tab after _only_ whitespace characters, be they tabs or spaces, the <Tab> press will erase all prior whitespace, then input the Tab.  If vim detected that we were on some level of indentation before hand, then the whitespace will be stripped beyond that level of indentation.

If a single non-whitespace character comes before the input on the line, then the tab is correctly input, without any backspaces occurring.

EDIT: After further testing, it seems that pressing tab after only whitespace doesn't just strip all whitespace - if <Tab> occurs in a line with no characters but whitespace, and there is a level of indentation assigned to this line, then the input will strip all whitespace, move the cursor to the indentation, and *then* input the Tab.

**Comment by rabirabirara** [comment]
I couldn't record my screen at the moment, but I can offer some screenshots of what happens.

I am currently heavily indented in a .jl file.  I have typed the letter k.  The cursor is also at that level of indentation.
![image](https://user-images.githubusercontent.com/59306451/91626154-7313d300-e961-11ea-8103-5a484c63f23a.png)

I decide that I want to type another k at a previous level of indentation.  I backspace somewhat and type 'k':
![image](https://user-images.githubusercontent.com/59306451/91626156-760ec380-e961-11ea-9580-e4b2b398e996.png)

I press tab.  For some reason, the k is moved to the current level of indentation, and the tab is then input.
![image](https://user-images.githubusercontent.com/59306451/91626162-8a52c080-e961-11ea-9ac7-908a0cb35a03.png)

If this is intended behavior, or changeable, then please do inform me!  The reason why I don't believe it is is because of this oddity:

If I open a new file, test.jl, and want to input a series of tabs, I cannot input more than one Tab.

This is my cursor on line number 4, having pressed Tab once.  If I press Tab any more times, the cursor does not move from that spot.

![image](https://user-images.githubusercontent.com/59306451/91626262-53c97580-e962-11ea-8c1f-a45c5ba5373c.png)

The expected behavior, as works without the plugin enabled, is for neovim to input more tab characters.

**Comment by carlobaldassi** [comment]
This was hopefully fixed in #251. Otherwise, please comment and I'll reopen.
