### ISSUE TITLE
Feature request: Indent by a constant after opening parenthesis

### ISSUE THREAD

**Issue by mhauru** [JuliaEditorSupport/julia-vim#207]
If I open a parenthesis of some kind, immediately followed by a linebreak, julia-vim currently indents things like this:
```
function my_function_names_have_a_habit_of_growing_very_long_but_i_secretly_enjoy_it(
                                                                                     arg1,
                                                                                     arg2,
                                                                                    )
    # function body at this level
end
```
I would instead prefer one of the following options:
```
function my_function_names_have_a_habit_of_growing_very_long_but_i_secretly_enjoy_it(
        arg1,
        arg2,
    )
    # function body at this level
end

# or

function my_function_names_have_a_habit_of_growing_very_long_but_i_secretly_enjoy_it(
    arg1,
    arg2,
)
    # function body at this level
end
```
This is the style followed by e.g. Python's [Black](https://github.com/psf/black/blob/master/docs/the_black_code_style.md) and the Julia style guide [Blue](https://github.com/invenia/BlueStyle#method-definitions). In Julia's standard library conventions vary, but I find several parts of it that use the style I'm proposing, or something similar.

If others prefer the current style, this could be an option for the user to set.

**Comment by tom--lee** [comment]
If you are desparate, I implemented the latter of your preferred options in my own fork: https://github.com/tom--lee/julia-vim . It is very hacky but it gets the job done.

**Comment by mhauru** [comment]
That's great, thanks! I may soon grow desperate. :) If the idea gets the blessing of the maintainers, that could also be the basis for a pull request.

**Comment by carlobaldassi** [comment]
I have now implemented your first option, and made it the default. The previous behavior can be restored with `g:julia_indent_align_funcargs=1`.

The new default is only for function arguments. To get the same behavior for all bracketed expressions use `g:julia_indent_align_brackets=0`.

See the docs for some examples.

**Comment by danielwe** [comment]
This is a great improvement, I was just looking into how to adjust this behavior this morning. However, given the choice I would strongly prefer the Blue-compliant style, i.e., @mhauru's second option,
```julia
function foo(
    bar,
    baz,
)
    return bar + baz
end
```
In other words, treating the argument tuple as any other tuple/array. Looks like @tom--lee made it work---any chance of incorporating that too as an option?
