### ISSUE TITLE
Behaviour of gg=G on docstrings

### ISSUE THREAD

**Issue by hkauhanen** [JuliaEditorSupport/julia-vim#210]
I often do a gg=G to reindent a file whose indentation has gone awry for whatever reason. This works great, except that julia-vim also indents docstrings. I'm not sure whether this is intended behaviour or not – however, it is problematic at least when the first line of the docstring is the signature of a function with the customary four-space indent. In other words, this:

```julia
"""
    myfun(foo::Bar)

Lorem, ipsum.
"""
function myfun(foo::Bar)
 print(foo)
                     end
```

is turned into

```julia
"""
myfun(foo::Bar)

Lorem, ipsum.
"""
function myfun(foo::Bar)
  print(foo)
end
```

by gg=G. Problem: Documenter.jl no longer prints the function signature as code, and I need to go and correct all instances by hand.

(Or am I doing something wrong/stupid?)

**Comment by carlobaldassi** [comment]
This should be already fixed with the latest version of the plugin, see #201. Indeed, your example works for me. Can you confirm and close if that's the case?
