### ISSUE TITLE
`TODO` comment strings no longer highlighted

### ISSUE THREAD

**Issue by ExpandingMan** [JuliaEditorSupport/julia-vim#213]
I'm not entirely sure if this is being caused by this package, but it seems to work for everything except Julia all of a sudden, so I think it's coming from here.

By default `nvim` used to highlight `TODO` appearing in comments.  This is a useful feature that I made frequent use of (I think it's built into vanilla `nvim`?).  I'm not seeing it anymore, only in `ft=julia`.  Anyone have any idea why?

**Comment by carlobaldassi** [comment]
Sorry, this was removed by accident, I have just restored it

**Comment by ExpandingMan** [comment]
Great, thanks!
