### ISSUE TITLE
Plugin overrides commentstring?

### ISSUE THREAD

**Issue by imLew** [JuliaEditorSupport/julia-vim#218]
I'm using tpope's vim-commentary plugin to comment lines and it's been working great with julia. However I now want to change the commentstring (to double `##` instead of single `#` to make it easier to work with Literate.jl) but the change has no effect on the comment behaviour when julia-vim is also enabled.

The commenstring variable can be correctly changed but it has no effect when julia-vim is in use. 
Is there any other way to change the commenstring?

**Comment by carlobaldassi** [comment]
From what I saw in the ftplugin files that come with natively supported languages, most set the commentstring with `setlocal`, just like in this plugin.
If you want to override it, you can create a file `.vim/after/ftplugin/julia.vim` and write `setlocal commentstring=##%s` in it.

**Comment by imLew** [comment]
Thanks for the reply, but I see now that "override" was not the best word choice.
It's not that I cannot set the commentstring, but that when julia-vim is active the commentstring is not being used. I.e. `set commentstring=##%s` does work (or I can set with ftplugin or autocmd) in the sense that `set commentstring?` returns `##%s`. The problem is that the actual commenting behaviour does not reflect this, comments are created with a single `#` no matter what the commentstring is.

**Comment by carlobaldassi** [comment]
Possibly vim-commentary only reads the commentstring once? I'm not sure. It seems to me to be an issue with that plugin, in any case.

**Comment by imLew** [comment]
No, if julia-vim is not active changing the commentstring changes the behaviour of vim-commentary. 
Do you know of any vim native behaviour that is affected by the commentstring? If that is not affected by julia-vim it's a commentary issue, otherwise I'd say it julia-vim.

**Comment by carlobaldassi** [comment]
So this is due to a previous issue with vim-commentary (#198) and the solution was to set the variable `b:commentary_format` in the plugin. (Sorry, I forgot about that...)
You can `:let b:commentary_format = "## %s"` to change it.
If you want to use it by default, it should be enough to write this in your config file:
```
autocmd FileType julia let b:commentary_format = "## %s"
```
In case this doesn't work well I can reopen the issue.

**Comment by imLew** [comment]
Thanks for coming back to this. 
This solution works :+1:
