### ISSUE TITLE
Latex-to-Unicode not working

### ISSUE THREAD

**Issue by Pastells** [JuliaEditorSupport/julia-vim#223]
I'm on ubuntu 20.04 with vim 8.1.2269.
The plugin seems to be correctly installed, all the documentations appers with :help julia-vim.
But it doesn't transform Latex to Unicode with either <Tab> or automatically with the option (let g:latex_to_unicode_auto = 1).

My minimal .vimrc:

set nocompatible              " be iMproved, required
filetype off                  " required
set encoding=utf-8
set t_Co=256
syntax on
set noshowmode

" --------- PLUGINS ---------------
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

    Plugin 'VundleVim/Vundle.vim'

    Plugin 'JuliaEditorSupport/julia-vim'
        let g:latex_to_unicode_auto = 1
call vundle#end()            " required
filetype plugin indent on    " required

" persistent undo
set undofile undodir=~/.vim/undodir
set history=1000        " maximum history

**Comment by Pastells** [comment]
It wasn't a problem with julia-vim. Vim was detecting .jl files as lisp.
I solved it thanks to phicr and Aerinmund Fagelson in https://stackoverflow.com/questions/42698782/julia-syntax-highlighting-in-julia-vim.

**Comment by carlobaldassi** [comment]
It would be nice to understand why .jl files are still recognized as lisp despite the attempt at overriding that behavior [here](https://github.com/JuliaEditorSupport/julia-vim/blob/e14fd34409de39025af93873adc6d26a831d70f9/ftdetect/julia.vim).
