### ISSUE TITLE
[BUG] Highlighting of Numbers within Variable Names

### ISSUE THREAD

**Issue by TheCedarPrince** [JuliaEditorSupport/julia-vim#227]
Thank you for the wonderful package and for supporting Julia for Vim! I use this every single day for several hours at a time.

I am seeing this strange behavior with variable names that have numbers:

![image](https://user-images.githubusercontent.com/29561456/105889066-c3a85e80-5fdb-11eb-819a-6a18927ce2f4.png)

I have the latest version of julia-vim installed so I am not sure what is going on as I expect the numbers within a string to not be highlighted. Thank you!

**Comment by carlobaldassi** [comment]
I can't reproduce this, for me both vim and neovim work as expected with these examples.
I'm also unable to guess what might be going on.
Something in your vimrc? Did you maybe add the `_` character as a word delimiter for some reason?

**Comment by TheCedarPrince** [comment]
Hunh! Let me get back to you @carlobaldassi - I will try to check things out to see what may be causing this issue with a minimal vimrc.

**Comment by carlobaldassi** [comment]
Good. In this case, the original issue was in your definition of the `iskeyword` variable, it likely doesn't include the underscore for some reason.
