### ISSUE TITLE
Add manual indentation within docstrings

### ISSUE THREAD

**Issue by albinahlback** [JuliaEditorSupport/julia-vim#229]
When writing docstrings, I find myself often writing a single line indented and the following lines with no indent, like:
```
"""
    foo(a)

Description.
"""
```
However, with the current settings I end up with
```
"""
    foo(a)

    Description.
    """
```

Is it possible to make a setting that `set noautoindent` within docstrings?

**Comment by carlobaldassi** [comment]
Isn't that just a matter of pressing a single backspace after the first line? The plugin already leaves docstrings as they are when indenting (#201, #210, #212). I don't know of a way to `set noautoindent` on a region.

**Comment by albinahlback** [comment]
Well, for me it's two backspaces since I use a tabsize of 2. It would be nice if there was a fix for this, but I understand that this wouldn't be a high priority.

**Comment by carlobaldassi** [comment]
I don't think there is a fix.
