### ISSUE TITLE
Add prefix for possible docstrings

### ISSUE THREAD

**Issue by albinahlback** [JuliaEditorSupport/julia-vim#230]
Docstrings can have multiple prefixes, like
```
"""
content
"""

@doc """
content
"""

@doc Markdown.doc"""
content
"""
```
I tried to include the last one by changing `^"""` to `^\(\s\|\)\(@doc\sMarkdown.doc\|\)` in `juliaDocString`, but it didn't work. I think the `@doc` messes it up since I get a `juliaStringPrefixed` when calling `:echo map(synstack(10,1), 'synIDattr(v:val, "name")')`

**Comment by carlobaldassi** [comment]
I have a fix for this at https://github.com/carlobaldassi/julia-vim/tree/moredocstrings (but it's on top of #231 so I'll wait for that to settle before committing), maybe in the meanwhile you may want to check if it works as expected.

**Comment by albinahlback** [comment]
Thanks!
