### ISSUE TITLE
Cover mathematical base-functions

### ISSUE THREAD

**Issue by albinahlback** [JuliaEditorSupport/julia-vim#232]
Would it be fitting to cover [these mathematical base-functions](https://docs.julialang.org/en/v1/base/math/) in julia-vim?

Edit: I am a volunteer in the case it is fitting.

**Comment by carlobaldassi** [comment]
Why the mathematical ones and not the rest?

**Comment by albinahlback** [comment]
Yes! But I'm not a volunteer for that one haha

**Comment by carlobaldassi** [comment]
I think this goes under #226 then.
