### ISSUE TITLE
Wrong parsing of highlight groups for functions in assignment form

### ISSUE THREAD

**Issue by mroavi** [JuliaEditorSupport/julia-vim#234]
This is a function definition in assignment form:
```
add(a,b) = a + b
```
`add` is highlighted as a `juliaModuleBlock` while it should be highlighted as a `juliaFunctionName`.

Another case:
```
Base.IndexStyle() = Base.IndexLinear()
```
`IndexStyle` is highlighted as `juliaBaseTypeArray` while I think it should be `juliaFunctionName`.

**Comment by carlobaldassi** [comment]
These should be fixed by #231 (they will actually all be highlighted as `JuliaFuncionCall`).

**Comment by mroavi** [comment]
This line shows up in my highlights:

![image](https://user-images.githubusercontent.com/19517248/109397494-240e2100-7937-11eb-9803-0427d31876d0.png)

and here is how the examples above appear highlighted:

![image](https://user-images.githubusercontent.com/19517248/109397316-62571080-7936-11eb-8856-62cd1031fbb3.png)
![image](https://user-images.githubusercontent.com/19517248/109397349-6a16b500-7936-11eb-8f76-9e980a0bf2bc.png)

**Comment by mroavi** [comment]
By the way, the piece of code I showed above is not a function call but rather a function definition (one with shorter syntax than the one that uses the `function` keyword, but they are equivalent)

**Comment by carlobaldassi** [comment]
Yes, but it will be fixed if/when #231 is merged.
As for detecting function definitions performed with assignments, I think it's basically impossible to do in any reasonable way with vim, because the `=` sign that determines the interpretation comes an arbitrary number of tokes after the function name, and thus the highlighting would need to go backwards (whereas vim highlighting proceeds in the forward direction only, with some very, very limited and expensive looking-back capabilities).

**Comment by mroavi** [comment]
Ohh I see. Thanks for the clarification!

**Comment by mroavi** [comment]
Sorry to bother you again but the problem doesn't seem to be fixed with the new updates:

![image](https://user-images.githubusercontent.com/19517248/109542654-a3c9f600-7ac5-11eb-8081-0fe862dab941.png)

The left `product` is a function name definition and should be highlighted with `juliaFunctionName`. The `product` in the right is a function call and it is correctly highlighted with `juliaFunctionCall`

**Comment by mroavi** [comment]
These two function definitions are equivelent, and hence should have the same color highlighting:

![image](https://user-images.githubusercontent.com/19517248/109544500-edb3db80-7ac7-11eb-80a9-3e681cdc4d74.png)

![image](https://user-images.githubusercontent.com/19517248/109544542-fb696100-7ac7-11eb-85e4-16b384f14a8a.png)

**Comment by carlobaldassi** [comment]
> As for detecting function definitions performed with assignments, I think it's basically impossible to do in any reasonable way with vim, because the = sign that determines the interpretation comes an arbitrary number of tokens after the function name, and thus the highlighting would need to go backwards (whereas vim highlighting proceeds in the forward direction only, with some very, very limited and expensive looking-back capabilities).

**Comment by mroavi** [comment]
Ohh right. Sorry I missed that. Hmm I wonder how VS Code or Atom do it.

**Comment by mroavi** [comment]
Would it be helpful if I ask one of the maintainers?

**Comment by carlobaldassi** [comment]
I think that they have a running julia session and leverage Julia itself for determining the syntactic role of each token. This is not how syntax highlighting (currently) works in vim.

**Comment by pfitzseb** [comment]
No, VSCode's syntax highlighting is regex based as well. We're matching short-form function definitions with [this](https://github.com/JuliaEditorSupport/atom-language-julia/blob/675c218e8c30d9b277064f0e6f87ff098b863f85/grammars/julia.cson#L154), which works ok in many cases (but can also very easily break, see e.g. https://github.com/JuliaEditorSupport/atom-language-julia/issues/240).

**Comment by carlobaldassi** [comment]
Ah I see, thanks for correcting me. Anyway, the problem with that regex is the arguments part `\\(.*\\)` which is what can so easily break. To do it right (in vim) one has to use a syntax region, opened by something like `"identifier("` and ended by `") ="`, but the opening matches both a function call and a function def, and there is no way to discriminate based on the ending part. And I can't think of any work around to obtain that effect.
