### ISSUE TITLE
customizable key in insert mode for latex-to-unicode

### ISSUE THREAD

**Issue by ExpandingMan** [JuliaEditorSupport/julia-vim#238]
This might be related to #224, but seemed distinct, so I thought it appropriate to open a new issue.

Latex-to-unicode works just fine for me about 95% of the time because simply preccing `<space>` or anything other special character completes it, but sometimes I am at the end of a line or something and sometimes (but not always) this *really* does not play nicely with deoplete, and I have to press tab several times to get it to complete.  This happens just enough that I have found myself getting into the bad habit of pressing `<space><backspace>` which I'm starting to feel will bite me eventually.

I have considered using something other than deoplete, but this has not worked out either, since LSP is still problematic enough to be extremely obnoxious and I very much rely on completions from matched text elsewhere in the file which deoplete seems to do better than everything else.

I'm pretty much out of ideas on how to alleviate this problem once and for all, but I'm wondering how hard it would be to create an option for allowing an insert-mode binding *other* than tab to complete?  It's not ideal, but in the absence of a real solution, it would still be a drastic improvement for me.

**Comment by ExpandingMan** [comment]
I'm super excited about this, that's been annoying me for a long time!  Thanks again!

**Comment by ExpandingMan** [comment]
Ok, much to my frustration, it seems that there are still some cases where this does not fix the problem.  I think it has helped, but I'm not entirely sure how or what exactly is going on.

If it's a helpful clue, note that now in all cases where it does not work I get the message
```
User defined completion ^U^P^N
```
flashing at me.  Might be a clue because I don't otherwise see this message.  As far as I can tell, it originates form somewhere in nvim and not necessarily in deoplete (though I'm sure deoplete still has something to do with it).

**Comment by carlobaldassi** [comment]
So is the problem still that pressing `<Tab>` after, say, `\alpha` sometimes has no effect? Do you have any clue about which circumstances seem to trigger it? Say, writing very fast, pressing Tab repeatedly...

**Comment by ExpandingMan** [comment]
It might be something to do with what suggestions are there...

It's very hard to reproduce consistently, so I made a gif for you.
![latex_deoplete_problem](https://user-images.githubusercontent.com/11379353/110042285-90ac6580-7d13-11eb-8129-434119f7f0d5.gif)

The first time I open `nvim`, I make a mistake, that deoplete tries to come up with some completion for, and it ruins the tabbing immediately.  The next time I open it, it seems to work until it has something to complete on, and then stops working.  So, in this example it looks a bit like it's *never* working as long as deoplete is coming up with suggestions, but that's not always the case.

Note that message flashing at the bottom near the end of the gif.  I see that message *only* when the tab completion is failing, so perhaps it's an important clue?

Also, you can see my current vim config [here](https://gitlab.com/ExpandingMan/dotfiles/-/blob/master/home/.config/nvim/init.vim).

**Comment by ExpandingMan** [comment]
I just did a bit more experimenting... the message flashing at the bottom also appears in many cases in which tab completion works properly, so it may not be the great clue I was hoping for.

**Comment by ExpandingMan** [comment]
One more thing: just for the hell of it, I thought I'd check whether tab completion worked reliably if I *completely removed* deoplete tab completion by removing the line
```
inoremap <expr><tab> pumvisible() ? "\<c-n>" : "\<tab>"
```
from my `init.vim`.

Note that this did *NOT* fix the problem: deoplete completion no longer worked, but latex tab completion still often failed, so that may be an interesting clue.

**Comment by carlobaldassi** [comment]
In case of any more issues, just write and I'll reopen.

**Comment by ExpandingMan** [comment]
I've been using this all day, it seems fixed!  I do notice that in some rare cases, if the latex character is part of an existing symbol, sometimes the deoplete completion suggestions will take precedence, but I think this should now be handled through deoplete somehow.  I'm pretty sure I only never saw that before because previously all those cases had just been broken.

Anyway, thanks *so much* for your persistence in fixing this!  It's a huge relief!  Now I just need to get out of the habit of doing `<space><backspace>` instead of `<tab>`. :smile:
