### ISSUE TITLE
Don't highlight function calls as types

### ISSUE THREAD

**Issue by ararslan** [JuliaEditorSupport/julia-vim#240]
Current behavior:
![image](https://user-images.githubusercontent.com/6396159/109737906-bd2d7980-7b7b-11eb-8efe-9a7c7a6e6f7f.png)
I think it would make more sense for function calls to be recognized after types so that these cases appear how they did prior to the recent type highlighting improvements.

**Comment by ararslan** [comment]
You're amazing, thanks Carlo!

**Comment by ararslan** [comment]
@carlobaldassi, it seems this still happens inside of curly braces, e.g. `NTuple{2,typeof(x)}`

**Comment by carlobaldassi** [comment]
@ararslan actually your example seems to work fine for me on master.

**Comment by ararslan** [comment]
Oh you're right, I had forgotten to update! :facepalm: Thanks!
