### ISSUE TITLE
some type parameters are now improperly recognized as symbols

### ISSUE THREAD

**Issue by ExpandingMan** [JuliaEditorSupport/julia-vim#241]
![2021-03-03-101714_343x92_scrot](https://user-images.githubusercontent.com/11379353/109827495-c6652780-7c09-11eb-983d-f2b09c17fe0f.png)

Think this is happening only after the very latest commits.

**Comment by ExpandingMan** [comment]
actually, it's worse than that, this also happens in function arguments
![2021-03-03-102033_216x52_scrot](https://user-images.githubusercontent.com/11379353/109827894-2360dd80-7c0a-11eb-838c-3d08d176be71.png)

**Comment by ExpandingMan** [comment]
If this occurred because of the change that was supposed to make `typeof` not be highlighted as a type in arguments, I think that behavior would be infinitely preferable to this one, so either an option or a documented way to change it back would be much appreciated

**Comment by ExpandingMan** [comment]
It's so hard to read this code, but I guess it must have been [this commit](https://github.com/JuliaEditorSupport/julia-vim/commit/a4219720a6ccbef5a102ab3cdc76b253f53ef0f0)?  Again, if there's no way to fix it (I know pure regex is very limiting and there's no way to actually analyze program logic here), I think it's probably safe to say most would prefer the previous behavior.

**Comment by carlobaldassi** [comment]
Sorry. My excuse is that the colon is ridiculously overloaded in Julia...

**Comment by ExpandingMan** [comment]
Goddamn, you are fast!  Looks pretty much perfect now, thanks!!
