### ISSUE TITLE
Consider making latex-to-unicode tab completion a separate package

### ISSUE THREAD

**Issue by tomchor** [JuliaEditorSupport/julia-vim#246]
The latex-to-unicode completion feature of this package has always works amazingly well for me. So well that I want to use to the same for other source codes! In particular I've been looking for a way to do that while writing Python.

Unfortunately I haven't been able to find a standalone plug in that does that, so that I was wondering if there's interest to make this specific part of `julia-vim` its own vim plugin. I think it would definitely be useful.

If not, do you have any suggestions for how to achieve what I want?

Thanks!

**Comment by carlobaldassi** [comment]
You can already use it on any file type you want ([docs](https://github.com/JuliaEditorSupport/julia-vim/blob/ebafbe4e5fbeee5f6af70fb46e51bd10b00fd589/doc/julia-vim-L2U.txt#L214)). For example, I have this in my vimrc:
```viml
let g:latex_to_unicode_file_types = ".*"
let g:latex_to_unicode_file_types_blacklist = ["tex", "plaintex", "md", "markdown"]
```
Additionally, I have mapped the F7 key to quickly enable/disable it independently of the file type:
```
noremap <expr> <F7> LaTeXtoUnicode#Toggle()
noremap! <expr> <F7> LaTeXtoUnicode#Toggle()
```

As for making it its own plugin, it would make sense of course. My biggest concern is that there is not a universal way to make it a dependency of julia-vim, so people would not get it in their default setup (contrary to the REPL and every other editor, as far as I know).

**Comment by tomchor** [comment]
Alright, that's awesome! I missed that part in the docs, sorry! (The more I learn about this plugin the more I like it it)
