### ISSUE TITLE
improper highlighting of symbols in pairs

### ISSUE THREAD

**Issue by ExpandingMan** [JuliaEditorSupport/julia-vim#255]
This started popping up after a recent update
![2021-04-16-101315_80x51_scrot](https://user-images.githubusercontent.com/11379353/115037355-61555080-9e9c-11eb-8b3b-2cc2f2e4ad26.png)

I think that it is seeing the `>:` and thinking it's a type operation.

Note that patterns like `:a=>:b` are fairly common because of DataFrames.jl.

**Comment by carlobaldassi** [comment]
Thanks. I got carried away with trying to simplify things...
