### ISSUE TITLE
Indentation following a list comprehension

### ISSUE THREAD

**Issue by stawaway** [JuliaEditorSupport/julia-vim#257]
I get automatic indentation whenever I write a list comprehension:
```
a = [i for i=1:10]
  # indent at the start of new line
```

**Comment by carlobaldassi** [comment]
I can't reproduce this, for me it works fine.
Can you give more specifics about your setup? Maybe test with a minimal vimrc?

**Comment by stawaway** [comment]
The error was coming from the following in the vimrc file:
`filetype indent on`
