### ISSUE TITLE
Feature request: please provide simpler structure

### ISSUE THREAD

**Issue by oblitum** [JuliaEditorSupport/julia-vim#263]
Hi. Thanks for the project.

I want to ask, and I think the vim community as a whole deserves better from official support channels: _please provide better, more idiomatic, vim support_.

We, vim and neovim developers, when looking for language-vim plugins, are often looking first and foremost for ftdetect/indent/syntax files. We often expect completion logic to come from extra plugins built specially for that. As of now julia-vim seems to be trying too much, and basic syntax files are being provided clobbered with code completion and Unicode conversion that's often conflicting with plugins many people use, like YCM, coc.nvim and others. I've browsed the source code and it looks like there's too much code logic in it. In the vim community, default mappings are generally frowned upon for example. As of now julia-vim is providing default mappings, completion and has to keep track of plugins it conflicts with, the thing is that is not fixed and new conflicting plugins will keep coming up while julia-vim stays as it's now.

**Comment by carlobaldassi** [comment]
The only things that the plugin provides beyond ftdetect/indent/syntax files are:
1. block structure recognition, which is also part of many language plugins and simply extends the built-in mappings like <kbd>[[</kbd>, and in any case is fully configurable
2. integration with the documentation via the default <kbd>K</kbd> key mapping
3. LaTeX-to-Unicode

Thus, I believe that despite the rather over-arching title, this issue only applies to LaTeX-to-Unicode. You'll correct me if I'm wrong.

So about that. First and foremost, the functionality can be disabled. Just `let g:latex_to_unicode_tab = "off"`. I have inspected again more carefully the startup-time cost of this: sourcing the related files takes 5ms on my laptop. Maybe we could reduce that to 1 or 2ms if we managed to make [loading the symbols table](https://github.com/JuliaEditorSupport/julia-vim/blob/2f35033a2141eea7a5a89ef8be438985781a9fcf/autoload/LaTeXtoUnicode.vim#L44) lazy, but that's tricky and I wouldn't consider it a high priority to be honest (making the syntax faster is a much more pressing matter). (PRs welcome.)

On the other hand, in my opinion it wouldn't be a good idea to provide a Julia plugin without this functionality: the language itself encourages the use of Unicode, its use is very widespread in the community of Julia developers, and every single plugin for other editors provides it in the same way as the Julia REPL, via LaTeX substitutions.

**Comment by oblitum** [comment]
Thanks for answer.

> First and foremost, the functionality can be disabled. Just `let g:latex_to_unicode_tab = "off"`

@JinraeKim see:

https://github.com/JuliaEditorSupport/julia-vim/blob/b04bdfee67a62e225fb36aa49a4806bb8c74b5aa/doc/julia-vim-L2U.txt#L278

Possibly [the following tip](https://github.com/fannheyward/coc-julia/issues/194#issuecomment-850945472) didn't work for you because you used value `0` instead of `"off"`:

> > I agree that this issue should be closed because there is nothing that can be done about this in coc-julia it seems. That said, @JinraeKim for what it's worth: I am also using `julia-vim` and `coc-julia` and have no issues with the combination.
> > I noticed one important difference between your vimrc and mine. You seem to have unicode completion enabled for `julia-vim`.
> > ```
> > let g:latex_to_unicode_keymap = 1  " to avoid conflict with coc-julia and
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > try replacing it with this:
> > ```
> > let g:latex_to_unicode_tab = 0
> > let g:latex_to_unicode_eager = 0
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > These settings disable the unicode completion of julia-vim. The point is that you don't really need them because `coc-julia` already does the unicode completion for you.
> 
> Unfortunately, this remedy also does not work for me.

Now about,

>  I have inspected again more carefully the startup-time cost of this: sourcing the related files takes 5ms on my laptop. Maybe we could reduce that to 1 or 2ms if we managed to make [loading the symbols table](https://github.com/JuliaEditorSupport/julia-vim/blob/2f35033a2141eea7a5a89ef8be438985781a9fcf/autoload/LaTeXtoUnicode.vim#L44) lazy, but that's tricky and I wouldn't consider it a high priority to be honest (making the syntax faster is a much more pressing matter). (PRs welcome.)
> 
> On the other hand, in my opinion it wouldn't be a good idea to provide a Julia plugin without this functionality: the language itself encourages the use of Unicode, its use is very widespread in the community of Julia developers, and every single plugin for other editors provides it in the same way as the Julia REPL, via LaTeX substitutions.

I have to check startuptime on my side again with `let g:latex_to_unicode_tab = "off"` to know whether it gets negligible, or there's difference, but despite that, I really don't like that such code logic is loaded for every buffer I open, regardless how fast it can get. I want it not to run at all, but [as commented previously](https://github.com/JuliaEditorSupport/julia-vim/issues/261#issuecomment-846414145)  on #261, it's not possible to lazy load it through the plugin manager due to how it's structured. Using `'JuliaEditorSupport/julia-vim', ft = 'julia'` in packer.nvim, nvim gives the following error anytime it starts, or any buffer is opened, because the missing functions has been explicitly not sourced until a Julia file is opened, but they're being referred for hooking in `autocmd`'s globally:

```
Error detected while processing BufEnter Autocommands for "*":
E117: Unknown function: LaTeXtoUnicode#Refresh
E5108: Error executing lua ...e/pack/packer/start/nvim-tree.lua/lua/nvim-tree/view.lua:128: Vim(call):E117: Unknown function: LaTeXtoUnicode#Refresh
```

https://github.com/JuliaEditorSupport/julia-vim/blob/2f35033a2141eea7a5a89ef8be438985781a9fcf/ftdetect/julia.vim#L10-L13

**Comment by oblitum** [comment]
I have checked startuptime again and indeed I can't reproduce my early timings, it's indeed fast enough, though I still disagree about the plugin defaults. It's really unexpected for me, as text file author, to have tab consumed by default on julia files (is it vim or repl...), which is often unneeded if one already makes use of coc-julia or any other smart thing.

Besides that, README states: "To disable this mapping, you can use the command `:let g:latex_to_unicode_tab = 0`", which is really confusing/conflicting with the `let g:latex_to_unicode_tab = "off"` information.

**Comment by carlobaldassi** [comment]
1. `let g:latex_to_unicode_tab = "off"` is the same as `0`. Using `0` is the older format, but it's still recognized. I had updated the docs but forgot to update the README, which I will do now. So that cannot be the origin of the issue with coc-julia. Moreover, with that option set to `"off"` or `0`, the plugin doesn't introduce any mappings for the <kbd>Tab</kbd> key at all, therefore that cannot possibly be the problem. @JinraeKim, if you are still having this problem, please open an issue here and we'll figure it out. In my tests, coc-julia worked just fine with julia-vim, with or without the LaTeXtoUnicode substitutions, under all possible option configurations. If that's not the case, it's a bug and needs to be fixed.
2. As for getting rid of the LaTeXtoUnicode part of the plugin. @oblitum, if the startup time is irrelevant and the functionality is disabled, I don't see what possible problem there could be that you absolutely don't want to have it on your computer. Even if you can't load the plugin lazily in packer.nvim or any other plugin manager, the vast majority of julia-vim code is loaded lazily anyway, so it doesn't matter. In any case, to get rid of the code, do this: remove [these lines](https://github.com/JuliaEditorSupport/julia-vim/blob/2f35033a2141eea7a5a89ef8be438985781a9fcf/ftdetect/julia.vim#L10-L23), then under the `"autoload"` directory remove the files `"LaTeXtoUnicode.vim"`, `"julia_latex_symbols.vim"` and `"generate_latex_symbols_table.jl"`. In this way, you'll have optimized your disk usage.
3. The plugin overrides the <kbd>Tab</kbd> on julia files, because as I said that's what nearly every Julia user expects and every other plugin for other editors does, but it tries very hard to only do that if there happens to be a LaTeX string before that, and to fall-back to whatever other behavior the key had before otherwise. It generally works. If not, please open an issue.

**Comment by carlobaldassi** [comment]
@JinraeKim sorry, I see that there is already an issue open about coc-julia, scratch what I wrote above.

**Comment by oblitum** [comment]
2. It's not solely about disk usage, which is the most irrelevant thing here, for me, it's about sourcing files, which requires VimScript parsing, plus whatever logic that julia-vim contains that may eventually fail, but which I don't wish to deal with unless I'm coding Julia. As of now, as-is, it can't be optionally loaded via package manager due to the latter, and is forcing unneeded VimL parsing to happen, globally.
3. I realize that, but for me as a vim author first, and Julia coder second, even when authoring Julia, this is unwanted. The fact that it's triggered only on special occasions magically makes it even harder to debug for someone that isn't expecting it to happen.

All in all, for me, julia-vim sets itself apart in behavior from 90% of the language supporting plugins I've hit in 15y+ of vimming...

**Comment by carlobaldassi** [comment]
I'll think about how to possibly try to separate the LaTeXtoUnicode functionality even further (while still having it on by default, and available for all file-types). Maybe it would be a step forward to figuring out how to have native julia support in vim/neovim (I don't think it's likely it would be accepted as-is).

**Comment by oblitum** [comment]
Nice.

**Comment by wbthomason** [comment]
I'd like to suggest (as I'm experiencing the same issue as @oblitum) that one possible workaround could be just checking the value of `g:latex_to_unicode_tab` as a guard around https://github.com/JuliaEditorSupport/julia-vim/blob/2f35033a2141eea7a5a89ef8be438985781a9fcf/ftdetect/julia.vim#L10-L13, to avoid setting these autocommands (and causing the lazy-load error) if L2U is going to be disabled by default.
