### ISSUE TITLE
Tab causes Neovim to freeze

### ISSUE THREAD

**Issue by johngilbert2000** [JuliaEditorSupport/julia-vim#270]
I am able to type Greek letters such as `α` with `\alpha` + <kbd>Tab</kbd>, for example, without any issues. I am also able to use <kbd>Tab</kbd> normally by typing <kbd>Ctrl</kbd> + <kbd>V</kbd> + <kbd>Tab</kbd>. However, if I forget to type <kbd>Ctrl</kbd>+<kbd>V</kbd> on a new line, hitting <kbd>Tab</kbd> in insert mode completely freezes my Vim, and the only way around it is to close my terminal and reopen the file, minus unsaved changes.

I'm using Neovim v0.4.3, with julia-vim and deoplete-julia plugins, and I only experience this issue when editing Julia files. I was able to get rid of this issue by using `:let g:latex_to_unicode_tab = "off"` and `:call LaTeXtoUnicode#Init()` as mentioned in the README, although this also got rid of the nice feature of being able to type fancy Greek letters, which is unfortunate.

**Comment by carlobaldassi** [comment]
I can't reproduce this problem with my config, even on nvim 4.3, but I'm not using deoplete-julia. My guess is that the issue is likely related to interactions with that plugin. I see it's no longer maintained though. Do you have the option to upgrade neovim to 0.5 and use something else, as advised on the julia-deoplete page?

**Comment by carlobaldassi** [comment]
By the way there are other ways to enter the fancy unicode characters without pressing tab, in particular [as-you-type](https://github.com/JuliaEditorSupport/julia-vim/blob/6ff9e9938badea96f64154f2991e165e8d340cf2/doc/julia-vim-L2U.txt#L171) and [keymap](https://github.com/JuliaEditorSupport/julia-vim/blob/6ff9e9938badea96f64154f2991e165e8d340cf2/doc/julia-vim-L2U.txt#L194).

**Comment by johngilbert2000** [comment]
Yeah I figured it might be due to my particular setup, but just wanted to mention the issue just in case. I'll play around with my setup later. In the meantime, switching the `latex_to_unicode_tab` feature off works fine for me
