### ISSUE TITLE
[Feature Request] Unicode Tab Completion in Julia Markdown Files

### ISSUE THREAD

**Issue by TheCedarPrince** [JuliaEditorSupport/julia-vim#274]
Hi Julia-Vim creators - this is an absolutely wonderful package and a real treat to work with! I have been using it everyday for over a year and frankly, this is an immensely reliable plugin and I super appreciate the work and constant updates to it.

A request that I have, and I do not know how difficult it is of an ask, is to enable unicode tab completion within Julia Markdown files. I saw that we have support for `.jmd` files now and have been using these daily for work and other projects (i.e. #237). I use unicode tab completion easily in my `.jl` files, but miss the ability to do it in `.jmd`. Would this be a feature you could add?

Thanks!

~ tcp 🌳

**Comment by carlobaldassi** [comment]
Hi and thanks. The unicode tab completion functionality can be enabled in any filetype you want. For example
```
let g:latex_to_unicode_file_types = ["julia", "markdown"]
```
See more about how this works with `:help julia-vim-L2U-file-types`.
You can even set it up to work on all file types by default with a few exceptions (this is what I do), and also [activate/it deactivate it on the fly regardless of the file type](https://github.com/JuliaEditorSupport/julia-vim#enabling-and-disabling-the-latex-to-unicode-functionality).
Feel free to ask here if something's unclear or missing.
