### ISSUE TITLE
something has changed in indentation of function arguments

### ISSUE THREAD

**Issue by avigliotti** [JuliaEditorSupport/julia-vim#281]
I just updated the plugin after deleting ~/.vim/ and I found that function arguments are not indented at the beginning of the parenthesis as it used to be, but are indented from the left margin, 

to be more specific, i used to get
```Julia
function my_func(x::Int,
                 y::Int)
      x+y
end
```
now I get
```Julia
function my_func(x::Int,
     y::Float)
     x+y
end
```
is there anything I can do to restore the old behavior, I found it made clearer to read the arguments of a function especially when there are many

thanks

**Comment by carlobaldassi** [comment]
Yes, there is https://github.com/JuliaEditorSupport/julia-vim/blob/e4972997fb5aee1c180e9840586a09553865cc20/doc/julia-vim.txt#L448

**Comment by avigliotti** [comment]
many thanks for the quick reply, that works perfectly!

btw removing the old .vim/ folder fixed the problem I was having with vim not folding multi-line comments,

many thanks again!
