### ISSUE TITLE
LaTeX to Unicode fails

### ISSUE THREAD

**Issue by Antomek** [JuliaEditorSupport/julia-vim#283]
Hello,

First off: thanks a lot for your work on this plugin, it looks great!

Everything appears to work for me (the block movements work, I can access the Julia documentation with `K`, etc.) except for the LaTeX to unicode functionality.
Whenever I try to write a unicode character and hit `<TAB>`, I simply get four spaces instead of a completion menu.
I checked my existing keybindings with `:map` but nothing had overridden the `<TAB>` key; it's simply not there (but the other julia-vim bindings are).

When trying the `completefunc` manually with `<C-X><C-U>` I got the error: `E764: Option 'completefunc' is not set`.
Is the LaTeX to unicode functionality not supposed to work out of the box?
Could I have installed some plugin that interferes?
(I am not using any autocomplete plugin, so that can't be it.)
I am using neovim 0.6.1.

Any help getting this to work would be appreciated!

**Comment by carlobaldassi** [comment]
The functionality is supposed to work out of the box on julia files, so this is strange.

Did you install the plugin from this repository? Or did you get the julia support that comes with with vim/neovim, which is a subset of what this plugin does?

**Comment by Antomek** [comment]
Found the culprit!

I was using the plugin from this repo, that was no the issue.
Turns out I also had [filetype.nvim](https://github.com/nathom/filetype.nvim) in my config, which was somehow messing with this plugin (at least the l2u functionality).
Not sure why that happened, as my filedetection still worked and some of the keybindings also kept working as mentioned above.
In hindsight it's not surprising though that changing the filedetection logic would interfere with this plugin though.

Anyways, I can do with a longer startup time for now, so the problem is solved!
Could be good to add this plugin to the warning list in the Readme, perhaps?

**Comment by carlobaldassi** [comment]
Thanks, I have added a note to the readme and the docs.
