### ISSUE TITLE
why not use digraph to input unicode, especially the Greek alphabet,

### ISSUE THREAD

**Issue by junyixu** [JuliaEditorSupport/julia-vim#309]
`:digraph` to see all digraph

for example, `<C-K>f*` is φ

**Comment by carlobaldassi** [comment]
I don't think I understand the issue. You can always use digraphs in vim if you prefer. This plugin supports the insertion method used by the julia REPL, which by the way features many more symbols than those available with vim's digraphs. But if you don't need this extra functionality you can simply not use it.

I'm closing this, but I can reopen in case I'm missing something.
