### ISSUE TITLE
LaTeXtoUnicode missing double guillemets « and »

### ISSUE THREAD

**Issue by SeSodesa** [JuliaEditorSupport/julia-vim#310]
As the title says, the double guillemet symbols `«` and `»` are missing from the possible set of LaTeX to Unicode tab expansions, even though they exist in the `UnicodeData.txt` database. The single guillemets `‹` and `›` are available via the commands `\guilsingleft` and `\guilsingright`, so a suitable pair of commands for the double guillemets might be added as `\guildoubleft` and `\guildoubright`, or just `\guildleft` and `\guildright`, if brevity is to be preferred.

**Comment by carlobaldassi** [comment]
These symbols are indeed present in UnicodeData.txt but not in the REPL completions, as you can see here: https://github.com/JuliaLang/julia/blob/ecca2c5a2f0719a306c44628736c8f6c8ac6453f/stdlib/REPL/src/latex_symbols.jl.
You may want to open an issue in the julia repo with this proposal. Looking e.g. at https://github.com/JuliaLang/julia/pull/38860 it should be simple to do a pull request too if there's interest.

**Comment by SeSodesa** [comment]
I made a related pull request ([link]) towards the Julia repo, and it is set to be merged at some point. Once that happens, julia-vim might be updated as well.

**Comment by SeSodesa** [comment]
The required [pull request] was merged.

[pull request]: https://github.com/JuliaLang/julia/pull/50399

**Comment by carlobaldassi** [comment]
Updated, thank you.
