### ISSUE TITLE
Accents over greek letters are displayed shifted

### ISSUE THREAD

**Issue by Gregstrq** [JuliaEditorSupport/julia-vim#316]
If I try to add an accent to a greek letter, then instead of being displayed directly on top of the latter, it is shifted to the right.
As an example, you can try `\phi<Tab>\tilde<Tab>`.

Interestingly enough, everything works well for normal letters, i.e., if I try `a\tilde<Tab>`, then the `tilde` accent is displayed directly on top of `a` as expected.

**Comment by carlobaldassi** [comment]
I believe this is an issue with the font you are using, since for me your example works. I also vaguely remember having seen this issue before. To confirm whether the issue is the font, you may try [julia mono](https://juliamono.netlify.app/).

**Comment by Gregstrq** [comment]
You may be right: with Julia Mono everything works as it is supposed to.
