### ISSUE TITLE
LaTeX-to-Unicode triggers on all instances no just /unicode. Supertab conflict?

### ISSUE THREAD

**Issue by floringogianu** [JuliaEditorSupport/julia-vim#39]
On MacVim 7.4 when pressing `<Tab>` for indenting (say at the beginning of a line), LaTeX-to-Unicode triggers and since there is nothing to match, it fallbacks to the vim-supertab mapping and lets me indent. 

However pressing `<Tab>` twice each time is not exactly ideal. Any idea how I can fix this conflict without deactivating LaTeX-to-Unicode?

**Comment by carlobaldassi** [comment]
Could you update the plugin and see if the problem is solved?

**Comment by floringogianu** [comment]
I apologize for the late reply. I updated the plugin but now the behavior is worse. It now triggers the autocomplete on **every** `<Tab>` press, with the suggestion preceded by `^F` characters. I'll try to reinstall the plugin today because right now it is not indenting at all.

Something like this: https://www.dropbox.com/s/pgrtt1pnnlg5ylk/Screenshot%202015-01-17%2016.34.59.png?dl=0

**Comment by carlobaldassi** [comment]
Can you tell me the output of this command?

```
:echo has("xim")
```

it should be 1 or 0, it gets printed on the command line.

I'm hoping it's `0`, but in case it's `1` instead can you then run `vim --verision` in the shell and paste the output here?

**Comment by carlobaldassi** [comment]
(BTW I believe the problem was in fact solved, and that what you see now is a new problem introduced later in the process of trying to be windows-compatible. I hate these portability issues...)

**Comment by floringogianu** [comment]
Thank you for following up with this. `:echo has("xim")` is `1`. Here is the complete output:

```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Dec 22 2014 09:47:20)
MacOS X (unix) version
Included patches: 1-258
Compiled by Homebrew
Huge version with MacVim GUI.  Features included (+) or not (-):
+acl             +file_in_path    +mouse_sgr       +tag_binary
+arabic          +find_in_path    -mouse_sysmouse  +tag_old_static
+autocmd         +float           +mouse_urxvt     -tag_any_white
+balloon_eval    +folding         +mouse_xterm     +tcl
+browse          -footer          +multi_byte      +terminfo
++builtin_terms  +fork()          +multi_lang      +termresponse
+byte_offset     +fullscreen      -mzscheme        +textobjects
+cindent         -gettext         +netbeans_intg   +title
+clientserver    -hangul_input    +odbeditor       +toolbar
+clipboard       +iconv           +path_extra      +transparency
+cmdline_compl   +insert_expand   +perl            +user_commands
+cmdline_hist    +jumplist        +persistent_undo +vertsplit
+cmdline_info    +keymap          +postscript      +virtualedit
+comments        +langmap         +printer         +visual
+conceal         +libcall         +profile         +visualextra
+cryptv          +linebreak       +python          +viminfo
+cscope          +lispindent      -python3         +vreplace
+cursorbind      +listcmds        +quickfix        +wildignore
+cursorshape     +localmap        +reltime         +wildmenu
+dialog_con_gui  -lua             +rightleft       +windows
+diff            +menu            +ruby            +writebackup
+digraphs        +mksession       +scrollbind      -X11
+dnd             +modify_fname    +signs           -xfontset
-ebcdic          +mouse           +smartindent     +xim
+emacs_tags      +mouseshape      -sniff           -xsmp
+eval            +mouse_dec       +startuptime     -xterm_clipboard
+ex_extra        -mouse_gpm       +statusline      -xterm_save
+extra_search    -mouse_jsbterm   -sun_workshop    -xpm
+farsi           +mouse_netterm   +syntax
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/Applications/MacVim.app/Contents/Resources/vim"
Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_MACVIM -Wall -Wno-unknown-pragmas -pipe  -DMACOS_X_UNIX  -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -fno-strict-aliasing -fno-common -dynamic -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -mmacosx-version-min=10.10 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1     -I/System/Library/Frameworks/Tcl.framework/Headers  -D_REENTRANT=1  -D_THREAD_SAFE=1  -D_DARWIN_C_SOURCE=1
Linking: clang   -L. -L/usr/local/lib -L. -L/usr/local/lib -L/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/config -framework CoreFoundation -lpython2.7 -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -mmacosx-version-min=10.10 -L/usr/local/lib -o Vim -framework Cocoa -framework Carbon       -lm  -lncurses -liconv -framework Cocoa   -fstack-protector  -L/System/Library/Perl/5.18/darwin-thread-multi-2level/CORE -lperl -framework Python  -F/System/Library/Frameworks -framework Tcl -framework CoreFoundation -framework Ruby
```

**Comment by carlobaldassi** [comment]
Ok thanks. I can't see anything obviously different and relevant between your version output and mine, and I can't test MacVim, so I'm going blind here. Can you test the latest commit and see if it works?

If it's still producing unexpected results, can you then try to change the value in [this line](https://github.com/JuliaLang/julia-vim/blob/9219225579940c41128d477a3bad7fb7a4d15e12/autoload/LaTeXtoUnicode.vim#L73) until you find something which works, e.g. change `0091` to `0006`, or `009d` or some other [control character](http://www.fileformat.info/info/unicode/category/Cc/list.htm)?

**Comment by glesica** [comment]
I believe I am getting the same, or a similar problem. I have [YouCompleteMe](https://valloric.github.io/YouCompleteMe/) installed, which normally handles tab completion. I get the following error when I hit tab to try to select an item from the autocomplete box:
```
E127: Cannot redefine function LaTeXtoUnicode#Tab: It is in use
```
If I clear the error by hitting tab again I get really wonky behavior wherein anything I type that triggers autocomplete gets deleted.

I tried all of the values suggested above, and a couple from the list, to no avail.

**Comment by glesica** [comment]
For now, I've gone back to b959ac419720e86fb7c04363d98c235c978df4c3 which doesn't seem to have the bug. Just FYI.

**Comment by floringogianu** [comment]
@glesica thanks, I eventually ended up doing just that, reverted to `19e7fa1 `

**Comment by carlobaldassi** [comment]
@glesica I think I fixed your problem with YouCompleteMe, since I could reproduce it. Could you try the latest version?

The problem reported in this issue is different though. So @glesica if you still have problems can you open a different issue?

@floringogianu: did you perhaps try the suggestions in my [previous comment](https://github.com/JuliaLang/julia-vim/issues/39#issuecomment-70407472)? No luck?

**Comment by floringogianu** [comment]
@carlobaldassi in the meantime I moved on to neocomplete, so I can't reproduce this anymore. Maybe it should be closed since no one seemed to report this since I opened the issue?
