### ISSUE TITLE
Goto local Declaration

### ISSUE THREAD

**Issue by drichardson** [JuliaEditorSupport/julia-vim#65]
This is an enhancement request to support vim's `gd` (Goto local Declaration) command. The way it's implemented in [vim-go](https://github.com/fatih/vim-go) is very nice: you move the cursor over a symbol and then enter `gd` command to jump to the definition of that symbol.

**Comment by carlobaldassi** [comment]
I have had a look at how it would be possible to implement this, but it's really very hard to do right in vimscript for a language like Julia.

On the other hand, this functionality is apparently available via LanguageServer.jl, at least in neovim, see [here](https://github.com/JuliaEditorSupport/LanguageServer.jl/wiki/Neovim).

I think there may be some experimental support for vim 8, but I haven't tested it.

Note that, as far as I can tell, vim-go also relies on an external parser for this, which is actually the sane way to do it.

And of course, there's always the poor man's way of just using <kbd>#</kbd>, at least within one file...
