### ISSUE TITLE
Add .travis.yml

### ISSUE THREAD

**Issue by Hydrotoast** [JuliaEditorSupport/julia-vim#75]
Since the plugin is enabled for pull requests. Otherwise all PRs will be marked with a failing build.

```
Could not find .travis.yml, using standard configuration.
```

**Comment by carlobaldassi** [comment]
Would make more sense to either disable travis or add tests. Volunteers for writing tests are welcome :)

I don't think I can disable Travis on this repo. @StefanKarpinski  could you do that?

**Comment by Hydrotoast** [comment]
@carlobaldassi I'm not sure I've ever seen anyone write tests for vimscript. I like the idea of disabling Travis if it's not helping though.

**Comment by carlobaldassi** [comment]
I have just disabled travis for this repository. Writing tests for vimscript would be possible in principle but it's a major pain (volunteers welcome).

(@tkelman thanks for granting me access!)
