### ISSUE TITLE
Improper unclosed parenthesis detection with updated Dict() constructor syntax

### ISSUE THREAD

**Issue by olsoni** [JuliaEditorSupport/julia-vim#81]
Julia version 0.5.0 changed dictionary construction syntax from: `d = [a => b for (a,b) in c]` to: `d = Dict(a => b for (a,b) in c)`. However, julia-vim seems to interpreting this as an improper parenthesis construction (ie the final parenthesis in this line will be highlighted as if it had no partner). This causes problems with syntax folding.

**Comment by carlobaldassi** [comment]
You just need to set the version to 0.5 in julia-vim and it will work, see https://github.com/JuliaLang/julia-vim/issues/71#issuecomment-243647980.

Now that Julia 0.5 is released, I'll need to drop support for 0.3 and make 0.5 the default.

**Comment by olsoni** [comment]
Thanks! that fix worked like a charm. I just added `let g:default_julia_version = "devel"` to my vimrc and all the syntax is perfect.

**Comment by carlobaldassi** [comment]
@olsoni note that I have just updated the plugin and now 0.5 is the default, while `"devel"` means 0.6. If you are staying on 0.5, you should change that line to `let g:default_julia_version = "current"` or just remove it (after you have updated, of course).
