### ISSUE TITLE
`String` type not being highlighted

### ISSUE THREAD

**Issue by ExpandingMan** [JuliaEditorSupport/julia-vim#82]
When I upgraded to the most recent commit I found that `String` was no longer be highlighted.  I wasn't too far behind so I think it's a fairly recent commit (in the last month or so) that broke this, but unfortunately I don't know exactly which one.

**Comment by carlobaldassi** [comment]
Thanks for reporting!

**Comment by ExpandingMan** [comment]
Thanks for the ultra-fast response!
