### ISSUE TITLE
highlighting of `$(...)`

### ISSUE THREAD

**Issue by ExpandingMan** [JuliaEditorSupport/julia-vim#83]
There is one more minor highlighting issue that remains: the boundaries of literal substitutions within expressions like `$(...)`.  To conform with the highlighting of `$x` and `:(...)`, the characters `$`, `(`, `)` would be highlighted.

Anyway @carlobaldassi just finished doing a great job on implementing symbol highlighting, and I thought I should express my appreciation for that after raising this other, probably rather obnoxious issue :smiley_cat:.

**Comment by carlobaldassi** [comment]
These are highlighted within Strings, but not in quoted expressions. Again, it boils down to the difficulty of disambiguating with the `$` used as xor. I think the easiest thing to do i wait for that use of `$` to [become deprecated](https://github.com/JuliaLang/julia/pull/18977), after which this can be safely implemented (until it's picked up for something else, of course). (Also thanks for the appreciation.)

**Comment by carlobaldassi** [comment]
Oh well.

**Comment by ExpandingMan** [comment]
Awesome, thanks.
