### ISSUE TITLE
Spurious error highlight for "end" when nesting macros

### ISSUE THREAD

**Issue by Evizero** [JuliaEditorSupport/julia-vim#85]
Hi!

After updating this vim plugin just now (which I don't do that regularly I admit, so I don't know what version I had last) the following code is now highlighted as being wrong syntactically, even though it works perfectly fine in 0.5 on OSX, and I think it is ok syntax-wise. 

```julia
using Base.Test
@testset "Test" begin
    @test @inferred(sin(0)) == 0
end
```  

It was fine before updating the plugin, so I reckon it must be some sideeffect of a recent change? 

<img width="324" alt="screen shot 2016-11-12 at 21 30 55" src="https://cloud.githubusercontent.com/assets/10854026/20240712/7ef76cee-a91f-11e6-9ecc-d8b03ef4c21a.png">

**Comment by carlobaldassi** [comment]
Thanks for reporting.

**Comment by Evizero** [comment]
That was quick! Works perfectly again. Thank you
