### ISSUE TITLE
invalid character after \@

### ISSUE THREAD

**Issue by bjarthur** [JuliaEditorSupport/julia-vim#86]
with vim 7.3 i still get the same error as reported [here](https://github.com/JuliaEditorSupport/julia-vim/issues/32)

```
Error detected while processing /Users/arthurb/.vim/syntax/julia.vim:
line  141:
E59: invalid character after \@
E475: Invalid argument: juliaModuleBlock^I^Imatchgroup=juliaBlKeyword start="\%(\.\s*\)\@6<!\<\%(bar
e\)\?module\>" end="\<end\>" contains=@juliaExpressions fold
```

upgrading to 7.4 fixes it

**Comment by CorbinFoucart** [comment]
I am getting the same error.  Version: VIM - Vi IMproved 7.2 (2008 Aug 9, compiled Apr  5 2012 10:17:30). I do not have the ability to upgrade to 7.4, unfortunately. Furthermore, when I exit the error message, the syntax is not highlighted at all.

**Comment by carlobaldassi** [comment]
I hope it's fixed now, and that it won't be too slow (those annotations are for performance reasons).

**Comment by CorbinFoucart** [comment]
Yes, it works great, thanks!
