### ISSUE TITLE
Matching square bracket in list comprehension

### ISSUE THREAD

**Issue by alvaro1101** [JuliaEditorSupport/julia-vim#91]
Hello:

If I split a list comprehension in two line like in the image I get a error in the closing square bracket.

![captura de pantalla de 2017-01-15 19 28 06](https://cloud.githubusercontent.com/assets/23438323/21965118/51ebe100-db59-11e6-82f1-382526293055.png)

Thanks.

**Comment by carlobaldassi** [comment]
Thanks for the report.
