### ISSUE TITLE
incorrect indentation after filtered generator expressions

### ISSUE THREAD

**Issue by ExpandingMan** [JuliaEditorSupport/julia-vim#95]
After writing a filtered generator expression, for example
```julia
[a for a ∈ A if a ≠ 0]
```
julia-vim will try to make the next line start with an indent, probably because it is recognizing the `if` token as the start of a conditional construct.  Note that this also happens if using `(` and `)` in place of `[` and `]` (in which case the expression returns a generator).

**Comment by carlobaldassi** [comment]
This should have been fixed by #90. Do you have the latest version of the plugin?

**Comment by ExpandingMan** [comment]
Ugh, embarrassing... I thought I did, because I saw that the last commit was months ago and could've sworn I've pulled since then... but I didn't.  Works fine.  Sorry!
